   <td>v0.0.50</td>
   <td>2019-01-09</td>
   <td><a title="fix bug editing code systems with property type mismatches" href="http://www.healthintersections.com.au/FhirServer/fhir-toolkit-install-0.0.50.exe"><img src="windows.ico"> Install</a></td>
   <td><a title="fix bug editing code systems with property type mismatches" href="http://www.healthintersections.com.au/FhirServer/fhir-toolkit-osx-0.0.50.zip"><img src="apple.png"> App</a></td>
