   <td>v0.0.63</td>
   <td>2020-02-01</td>
   <td><a title="More OSX 64bit release testing Again" href="http://www.healthintersections.com.au/FhirServer/fhir-toolkit-install-0.0.63.exe"><img src="windows.ico"> Install</a></td>
   <td><a title="More OSX 64bit release testing Again" href="http://www.healthintersections.com.au/FhirServer/fhir-toolkit-osx-0.0.63.zip"><img src="apple.png"> App</a></td>
