   <td>v0.0.58</td>
   <td>2019-09-06</td>
   <td><a title="fix R4 loading issue + code system editing issue" href="http://www.healthintersections.com.au/FhirServer/fhir-toolkit-install-0.0.58.exe"><img src="windows.ico"> Install</a></td>
   <td><a title="fix R4 loading issue + code system editing issue" href="http://www.healthintersections.com.au/FhirServer/fhir-toolkit-osx-0.0.58.zip"><img src="apple.png"> App</a></td>
