// JCL_DEBUG_EXPERT_INSERTJDBG ON
program FHIRServer;

{
Copyright (c) 2001-2013, Health Intersections Pty Ltd (http://www.healthintersections.com.au)
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of HL7 nor the names of its contributors may be used to
   endorse or promote products derived from this software without specific
   prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
}


{$APPTYPE CONSOLE}

{$R *.res}


{
todo:
STU3 draft:
 - check using UTF-8 in URLs
 - check prepfer = operation outcome
 - check turtle support
 - check versioning in capabilities statement
 - check elements & summary on read/vread
 - check delete return codes
 - changes to id element on update
 - check conditional delete flag.
 - search on multiple resource types
 - check over transaction handling
 - dateTIme parameter on history
 - check use of 401 instead of 403
 - check handling of unsupported parameters
 - check implementations of sa and be prefixes in search
 - review searching on names
 - check search by canonical URL and version
 - add searching for token system|
 - reverse chaining
 - check _list parameter
 - check sorting
 - check handling count = 0
 - composite search parameter work
 - test flag support
 - check document operation
 - check handling binary parameter
 - update FHIR.Version.PathEngine
 - string validation rules
 - Both _include and _revInclude use the wild card "*" for the search parameter name, indicating that any search parameter of type=reference be included.






Add reverse chaining
Grahame, I see you don't respond to either of the following:
 http://hl7connect.healthintersections.com.au/svc/fhir/condition/search?subject=patient/350
 http://hl7connect.healthintersections.com.au/svc/fhir/condition/search?subject=patient/@350
cross resource search
FHIR.Ucum.Base search

}

uses
  FastMM4 in '..\dependencies\FMM\FastMM4.pas',
  FastMM4Messages in '..\dependencies\FMM\FastMM4Messages.pas',
  Windows,
  SysUtils,
  Classes,
  IdSSLOpenSSLHeaders,
  IdCustomHTTPServer,
  MarkdownCommonMark in '..\..\markdown\source\MarkdownCommonMark.pas',
  MarkdownDaringFireball in '..\..\markdown\source\MarkdownDaringFireball.pas',
  MarkdownProcessor in '..\..\markdown\source\MarkdownProcessor.pas',
  fhir_common in '..\library\base\fhir_common.pas',
  fhir_factory in '..\library\base\fhir_factory.pas',
  fhir_narrative in '..\library\base\fhir_narrative.pas',
  fhir_objects in '..\library\base\fhir_objects.pas',
  fhir_parser in '..\library\base\fhir_parser.pas',
  fhir_pathengine in '..\library\base\fhir_pathengine.pas',
  fsl_scim in '..\library\base\fsl_scim.pas',
  fhir_utilities in '..\library\base\fhir_utilities.pas',
  fhir_validator in '..\library\base\fhir_validator.pas',
  fhir_xhtml in '..\library\base\fhir_xhtml.pas',
  fsl_npm_cache in '..\library\npm\fsl_npm_cache.pas',
  FHIR.CdsHooks.Server in 'FHIR.CdsHooks.Server.pas',
  FHIR.CdsHooks.Service in 'FHIR.CdsHooks.Service.pas',
  fhir_cdshooks in '..\library\cdshooks\fhir_cdshooks.pas',
  fhir_client in '..\library\client\fhir_client.pas',
  fhir_client_http in '..\library\client\fhir_client_http.pas',
  fhir_client_threaded in '..\library\client\fhir_client_threaded.pas',
  FHIR.Database.Dialects in '..\library\database\FHIR.Database.Dialects.pas',
  FHIR.Database.Logging in '..\library\database\FHIR.Database.Logging.pas',
  FHIR.Database.Manager in '..\library\database\FHIR.Database.Manager.pas',
  FHIR.Database.ODBC in '..\library\database\FHIR.Database.ODBC.pas',
  FHIR.Database.ODBC.Headers in '..\library\database\FHIR.Database.ODBC.Headers.pas',
  FHIR.Database.ODBC.Objects in '..\library\database\FHIR.Database.ODBC.Objects.pas',
  FHIR.Database.SQLite in '..\library\database\FHIR.Database.SQLite.pas',
  FHIR.Database.SQLite3.Objects in '..\library\database\FHIR.Database.SQLite3.Objects.pas',
  FHIR.Database.SQLite3.Utilities in '..\library\database\FHIR.Database.SQLite3.Utilities.pas',
  FHIR.Database.SQLite3.Wrapper in '..\library\database\FHIR.Database.SQLite3.Wrapper.pas',
  FHIR.Loinc.Importer in '..\library\loinc\FHIR.Loinc.Importer.pas',
  FHIR.Loinc.Publisher in '..\library\loinc\FHIR.Loinc.Publisher.pas',
  FHIR.Loinc.Services in '..\library\loinc\FHIR.Loinc.Services.pas',
  fsl_twilio in '..\library\web\fsl_twilio.pas',
  fhir2_base in '..\library\r2\fhir2_base.pas',
  fhir2_client in '..\library\r2\fhir2_client.pas',
  fhir2_common in '..\library\r2\fhir2_common.pas',
  fhir2_constants in '..\library\r2\fhir2_constants.pas',
  fhir2_context in '..\library\r2\fhir2_context.pas',
  fhir2_elementmodel in '..\library\r2\fhir2_elementmodel.pas',
  fhir2_factory in '..\library\r2\fhir2_factory.pas',
  fhir2_json in '..\library\r2\fhir2_json.pas',
  fhir2_narrative in '..\library\r2\fhir2_narrative.pas',
  fhir2_opbase in '..\library\r2\fhir2_opbase.pas',
  fhir2_operations in '..\library\r2\fhir2_operations.pas',
  fhir2_parser in '..\library\r2\fhir2_parser.pas',
  fhir2_parserBase in '..\library\r2\fhir2_parserBase.pas',
  fhir2_pathengine in '..\library\r2\fhir2_pathengine.pas',
  fhir2_pathnode in '..\library\r2\fhir2_pathnode.pas',
  fhir2_profiles in '..\library\r2\fhir2_profiles.pas',
  fhir2_resources in '..\library\r2\fhir2_resources.pas',
  fhir2_types in '..\library\r2\fhir2_types.pas',
  fhir2_utilities in '..\library\r2\fhir2_utilities.pas',
  fhir2_validator in '..\library\r2\fhir2_validator.pas',
  fhir2_xml in '..\library\r2\fhir2_xml.pas',
  fhir3_base in '..\library\r3\fhir3_base.pas',
  fhir3_client in '..\library\r3\fhir3_client.pas',
  fhir3_common in '..\library\r3\fhir3_common.pas',
  fhir3_constants in '..\library\r3\fhir3_constants.pas',
  fhir3_context in '..\library\r3\fhir3_context.pas',
  fhir3_elementmodel in '..\library\r3\fhir3_elementmodel.pas',
  fhir3_factory in '..\library\r3\fhir3_factory.pas',
  fhir3_json in '..\library\r3\fhir3_json.pas',
  fhir3_narrative in '..\library\r3\fhir3_narrative.pas',
  fhir3_opbase in '..\library\r3\fhir3_opbase.pas',
  fhir3_operations in '..\library\r3\fhir3_operations.pas',
  fhir3_parser in '..\library\r3\fhir3_parser.pas',
  fhir3_parserBase in '..\library\r3\fhir3_parserBase.pas',
  fhir3_pathengine in '..\library\r3\fhir3_pathengine.pas',
  fhir3_pathnode in '..\library\r3\fhir3_pathnode.pas',
  fhir3_profiles in '..\library\r3\fhir3_profiles.pas',
  fhir3_resources in '..\library\r3\fhir3_resources.pas',
  fhir3_turtle in '..\library\r3\fhir3_turtle.pas',
  fhir3_types in '..\library\r3\fhir3_types.pas',
  fhir3_utilities in '..\library\r3\fhir3_utilities.pas',
  fhir3_validator in '..\library\r3\fhir3_validator.pas',
  fhir3_xml in '..\library\r3\fhir3_xml.pas',
  fhir4_authmap in '..\library\r4\fhir4_authmap.pas',
  fhir4_base in '..\library\r4\fhir4_base.pas',
  fhir4_client in '..\library\r4\fhir4_client.pas',
  fhir4_common in '..\library\r4\fhir4_common.pas',
  fhir4_constants in '..\library\r4\fhir4_constants.pas',
  fhir4_context in '..\library\r4\fhir4_context.pas',
  fhir4_elementmodel in '..\library\r4\fhir4_elementmodel.pas',
  fhir4_factory in '..\library\r4\fhir4_factory.pas',
  fhir4_indexinfo in '..\library\r4\fhir4_indexinfo.pas',
  fhir4_json in '..\library\r4\fhir4_json.pas',
  fhir4_maputils in '..\library\r4\fhir4_maputils.pas',
  fhir4_narrative in '..\library\r4\fhir4_narrative.pas',
  fhir4_narrative2 in '..\library\r4\fhir4_narrative2.pas',
  fhir4_opbase in '..\library\r4\fhir4_opbase.pas',
  fhir4_operations in '..\library\r4\fhir4_operations.pas',
  fhir4_parser in '..\library\r4\fhir4_parser.pas',
  fhir4_parserBase in '..\library\r4\fhir4_parserBase.pas',
  fhir4_pathengine in '..\library\r4\fhir4_pathengine.pas',
  fhir4_pathnode in '..\library\r4\fhir4_pathnode.pas',
  fhir4_profiles in '..\library\r4\fhir4_profiles.pas',
  fhir4_questionnaire in '..\library\r4\fhir4_questionnaire.pas',
  fhir4_resources in '..\library\r4\fhir4_resources.pas',
  fhir4_turtle in '..\library\r4\fhir4_turtle.pas',
  fhir4_types in '..\library\r4\fhir4_types.pas',
  fhir4_utilities in '..\library\r4\fhir4_utilities.pas',
  fhir4_validator in '..\library\r4\fhir4_validator.pas',
  fhir4_xml in '..\library\r4\fhir4_xml.pas',
  FHIR.Scim.Search in 'FHIR.Scim.Search.pas',
  FHIR.Scim.Server in 'FHIR.Scim.Server.pas',
  FHIR.Server.AccessControl in 'FHIR.Server.AccessControl.pas',
  FHIR.Server.AuthMgr in 'FHIR.Server.AuthMgr.pas',
  FHIR.Server.ClosureMgr in 'FHIR.Server.ClosureMgr.pas',
  FHIR.Server.Constants in 'FHIR.Server.Constants.pas',
  FHIR.Server.DBInstaller in 'FHIR.Server.DBInstaller.pas',
  FHIR.Server.Database in 'FHIR.Server.Database.pas',
  FHIR.Server.GraphDefinition in 'FHIR.Server.GraphDefinition.pas',
  FHIR.Server.Jwt in 'FHIR.Server.Jwt.pas',
  FHIR.Server.Kernel in 'FHIR.Server.Kernel.pas',
  FHIR.Server.MpiSearch in 'FHIR.Server.MpiSearch.pas',
  FHIR.Server.ObsStats in 'FHIR.Server.ObsStats.pas',
  FHIR.Server.ReverseClient in 'FHIR.Server.ReverseClient.pas',
  FHIR.Server.Search in 'FHIR.Server.Search.pas',
  FHIR.Server.SearchSyntax in 'FHIR.Server.SearchSyntax.pas',
  FHIR.Server.Security in '..\library\tools\FHIR.Server.Security.pas',
  FHIR.Server.Session in '..\library\tools\FHIR.Server.Session.pas',
  FHIR.Server.Storage in 'FHIR.Server.Storage.pas',
  FHIR.Server.Subscriptions in 'FHIR.Server.Subscriptions.pas',
  FHIR.Server.UserMgr in 'FHIR.Server.UserMgr.pas',
  FHIR.Server.Utilities in 'FHIR.Server.Utilities.pas',
  FHIR.Server.Web in 'FHIR.Server.Web.pas',
  FHIR.Server.WebSource in 'FHIR.Server.WebSource.pas',
  FHIR.Server.XhtmlComp in 'FHIR.Server.XhtmlComp.pas',
  fhir_oauth in '..\library\smart\fhir_oauth.pas',
  FHIR.Snomed.Analysis in '..\library\snomed\FHIR.Snomed.Analysis.pas',
  FHIR.Snomed.Expressions in '..\library\snomed\FHIR.Snomed.Expressions.pas',
  FHIR.Snomed.Importer in '..\library\snomed\FHIR.Snomed.Importer.pas',
  FHIR.Snomed.Publisher in '..\library\snomed\FHIR.Snomed.Publisher.pas',
  FHIR.Snomed.Services in '..\library\Snomed\FHIR.Snomed.Services.pas',
  fsl_base in '..\library\Support\fsl_base.pas',
  fsl_crypto in '..\library\web\fsl_crypto.pas',
  fsl_collections in '..\library\Support\fsl_collections.pas',
  fsl_fpc in '..\library\support\fsl_fpc.pas',
  fsl_json in '..\library\Support\fsl_json.pas',
  fsl_logging in '..\library\support\fsl_logging.pas',
  fsl_xml in '..\library\support\fsl_xml.pas',
  fsl_msxml in '..\library\support\fsl_msxml.pas',
  fsl_service_win in '..\library\support\fsl_service_win.pas',
  fsl_shell in '..\library\Support\fsl_shell.pas',
  fsl_openssl in '..\library\web\fsl_openssl.pas',
  fsl_stream in '..\library\Support\fsl_stream.pas',
  fsl_threads in '..\library\support\fsl_threads.pas',
  fsl_turtle in '..\library\support\fsl_turtle.pas',
  fsl_utilities in '..\library\Support\fsl_utilities.pas',
  FHIR.Tools.CodeGen in '..\library\tools\FHIR.Tools.CodeGen.pas',
  FHIR.Tools.DiffEngine in '..\library\tools\FHIR.Tools.DiffEngine.pas',
  FHIR.Tools.GraphQL in '..\library\tools\FHIR.Tools.GraphQL.pas',
  FHIR.Tools.Indexing in '..\library\tools\FHIR.Tools.Indexing.pas',
  FHIR.Tx.ACIR in 'FHIR.Tx.ACIR.pas',
  FHIR.Tx.CountryCode in 'FHIR.Tx.CountryCode.pas',
  FHIR.Tx.Iso4217 in 'FHIR.Tx.Iso4217.pas',
  FHIR.Tx.Lang in 'FHIR.Tx.Lang.pas',
  FHIR.Tx.Manager in 'FHIR.Tx.Manager.pas',
  FHIR.Tx.MimeTypes in 'FHIR.Tx.MimeTypes.pas',
  FHIR.Tx.Operations in 'FHIR.Tx.Operations.pas',
  FHIR.Tx.RxNorm in 'FHIR.Tx.RxNorm.pas',
  FHIR.Tx.Server in 'FHIR.Tx.Server.pas',
  FHIR.Tx.Service in '..\library\FHIR.Tx.Service.pas',
  FHIR.Tx.Unii in 'FHIR.Tx.Unii.pas',
  FHIR.Tx.Uri in 'FHIR.Tx.Uri.pas',
  FHIR.Tx.UsState in 'FHIR.Tx.UsState.pas',
  FHIR.Tx.Web in 'FHIR.Tx.Web.pas',
  FHIR.Ucum.Base in '..\library\Ucum\FHIR.Ucum.Base.pas',
  FHIR.Ucum.Expressions in '..\library\Ucum\FHIR.Ucum.Expressions.pas',
  FHIR.Ucum.Handlers in '..\library\Ucum\FHIR.Ucum.Handlers.pas',
  fhir_ucum in '..\library\ucum\fhir_ucum.pas',
  FHIR.Ucum.Search in '..\library\Ucum\FHIR.Ucum.Search.pas',
  FHIR.Ucum.Services in '..\library\Ucum\FHIR.Ucum.Services.pas',
  FHIR.Ucum.Validators in '..\library\Ucum\FHIR.Ucum.Validators.pas',
  fsl_scrypt in '..\library\support\fsl_scrypt.pas',
  fsl_oauth in '..\library\web\fsl_oauth.pas',
  fsl_fetcher in '..\library\web\fsl_fetcher.pas',
  fsl_graphql in '..\library\web\fsl_graphql.pas',
  fhir_htmlgen in '..\library\web\fhir_htmlgen.pas',
  fsl_http in '..\library\web\fsl_http.pas',
  fsl_rdf in '..\library\web\fsl_rdf.pas',
  fsl_websocket in '..\library\web\fsl_websocket.pas',
  fsl_wininet in '..\library\web\fsl_wininet.pas',
  FHIR.XVersion.ConvBase in '..\library\xversion\FHIR.XVersion.ConvBase.pas',
  FHIR.Server.Tags in 'FHIR.Server.Tags.pas',
  FHIR.Tools.CodeSystemProvider in '..\library\tools\FHIR.Tools.CodeSystemProvider.pas',
  FHIR.Tools.ValueSets in '..\library\tools\FHIR.Tools.ValueSets.pas',
  FHIR.Server.Context in 'FHIR.Server.Context.pas',
  FHIR.Server.Indexing in 'FHIR.Server.Indexing.pas',
  fhir2_indexinfo in '..\library\r2\fhir2_indexinfo.pas',
  fhir3_indexinfo in '..\library\r3\fhir3_indexinfo.pas',
  fhir2_authmap in '..\library\r2\fhir2_authmap.pas',
  fhir3_authmap in '..\library\r3\fhir3_authmap.pas',
  fhir4_graphdefinition in '..\library\r4\fhir4_graphdefinition.pas',
  fhir_graphdefinition in '..\library\base\fhir_graphdefinition.pas',
  FHIR.Server.BundleBuilder in 'FHIR.Server.BundleBuilder.pas',
  FHIR.Server.IndexingR4 in 'FHIR.Server.IndexingR4.pas',
  FHIR.Server.IndexingR3 in 'FHIR.Server.IndexingR3.pas',
  FHIR.Server.IndexingR2 in 'FHIR.Server.IndexingR2.pas',
  FHIR.Server.OperationsR2 in 'FHIR.Server.OperationsR2.pas',
  FHIR.Server.OperationsR3 in 'FHIR.Server.OperationsR3.pas',
  FHIR.Server.OperationsR4 in 'FHIR.Server.OperationsR4.pas',
  FHIR.Server.SubscriptionsR2 in 'FHIR.Server.SubscriptionsR2.pas',
  FHIR.Server.SubscriptionsR3 in 'FHIR.Server.SubscriptionsR3.pas',
  FHIR.Server.SubscriptionsR4 in 'FHIR.Server.SubscriptionsR4.pas',
  fhir2_questionnaire in '..\library\r2\fhir2_questionnaire.pas',
  fhir2_narrative2 in '..\library\r2\fhir2_narrative2.pas',
  fhir3_questionnaire in '..\library\r3\fhir3_questionnaire.pas',
  fhir3_narrative2 in '..\library\r3\fhir3_narrative2.pas',
  FHIR.XVersion.Convertors in '..\library\xversion\FHIR.XVersion.Convertors.pas',
  FHIR.XVersion.Conv_30_40 in '..\library\xversion\FHIR.XVersion.Conv_30_40.pas',
  FHIR.Tools.NDJsonParser in '..\library\tools\FHIR.Tools.NDJsonParser.pas',
  FHIR.Server.Factory in 'FHIR.Server.Factory.pas',
  FHIR.Server.ValidatorR4 in 'FHIR.Server.ValidatorR4.pas',
  FHIR.Server.ValidatorR2 in 'FHIR.Server.ValidatorR2.pas',
  FHIR.Server.ValidatorR3 in 'FHIR.Server.ValidatorR3.pas',
  FHIR.Server.SessionMgr in 'FHIR.Server.SessionMgr.pas',
  VirtualTrees.Actions in '..\dependencies\treeview\Source\VirtualTrees.Actions.pas',
  VirtualTrees.Classes in '..\dependencies\treeview\Source\VirtualTrees.Classes.pas',
  VirtualTrees.ClipBoard in '..\dependencies\treeview\Source\VirtualTrees.ClipBoard.pas',
  VirtualTrees.Export in '..\dependencies\treeview\Source\VirtualTrees.Export.pas',
  VirtualTrees in '..\dependencies\treeview\Source\VirtualTrees.pas',
  VirtualTrees.StyleHooks in '..\dependencies\treeview\Source\VirtualTrees.StyleHooks.pas',
  VirtualTrees.Utils in '..\dependencies\treeview\Source\VirtualTrees.Utils.pas',
  VirtualTrees.WorkerThread in '..\dependencies\treeview\Source\VirtualTrees.WorkerThread.pas',
  VTAccessibility in '..\dependencies\treeview\Source\VTAccessibility.pas',
  VTAccessibilityFactory in '..\dependencies\treeview\Source\VTAccessibilityFactory.pas',
  VTHeaderPopup in '..\dependencies\treeview\Source\VTHeaderPopup.pas',
  FHIR.Npm.Browser in '..\library\npm\FHIR.Npm.Browser.pas' {PackageFinderForm},
  FHIR.Snomed.Combiner in '..\library\snomed\FHIR.Snomed.Combiner.pas',
  FHIR.Support.Lang in '..\library\support\FHIR.Support.Lang.pas',
  JclDebug in '..\dependencies\jcl\JclDebug.pas',
  JclBase in '..\dependencies\jcl\JclBase.pas',
  JclResources in '..\dependencies\jcl\JclResources.pas',
  JclFileUtils in '..\dependencies\jcl\JclFileUtils.pas',
  JclWin32 in '..\dependencies\jcl\JclWin32.pas',
  JclSysUtils in '..\dependencies\jcl\JclSysUtils.pas',
  JclSynch in '..\dependencies\jcl\JclSynch.pas',
  JclLogic in '..\dependencies\jcl\JclLogic.pas',
  JclRegistry in '..\dependencies\jcl\JclRegistry.pas',
  JclStrings in '..\dependencies\jcl\JclStrings.pas',
  JclAnsiStrings in '..\dependencies\jcl\JclAnsiStrings.pas',
  JclStreams in '..\dependencies\jcl\JclStreams.pas',
  JclStringConversions in '..\dependencies\jcl\JclStringConversions.pas',
  JclCharsets in '..\dependencies\jcl\JclCharsets.pas',
  JclMath in '..\dependencies\jcl\JclMath.pas',
  Jcl8087 in '..\dependencies\jcl\Jcl8087.pas',
  JclConsole in '..\dependencies\jcl\JclConsole.pas',
  JclShell in '..\dependencies\jcl\JclShell.pas',
  JclWideStrings in '..\dependencies\jcl\JclWideStrings.pas',
  JclUnicode in '..\dependencies\jcl\JclUnicode.pas',
  JclSysInfo in '..\dependencies\jcl\JclSysInfo.pas',
  Snmp in '..\dependencies\jcl\Snmp.pas',
  JclIniFiles in '..\dependencies\jcl\JclIniFiles.pas',
  JclSecurity in '..\dependencies\jcl\JclSecurity.pas',
  JclDateTime in '..\dependencies\jcl\JclDateTime.pas',
  JclPeImage in '..\dependencies\jcl\JclPeImage.pas',
  JclTD32 in '..\dependencies\jcl\JclTD32.pas',
  JclHookExcept in '..\dependencies\jcl\JclHookExcept.pas',
  FHIR.Server.v2Server in 'FHIR.Server.v2Server.pas',
  v2_protocol in '..\library\v2\v2_protocol.pas',
  v2_message in '..\library\v2\v2_message.pas',
  cda_narrative in '..\library\cda\cda_narrative.pas',
  fhir_oids in '..\library\base\fhir_oids.pas',
  fhir_elementmodel in '..\library\base\fhir_elementmodel.pas',
  Compat in '..\dependencies\chakracore-delphi\Compat.pas',
  MarkdownHTMLEntities in '..\..\markdown\source\MarkdownHTMLEntities.pas',
  FHIR.Server.ConsentEngine in 'FHIR.Server.ConsentEngine.pas',
  FHIR.Tx.NDC in 'FHIR.Tx.NDC.pas',
  FHIR.Ui.TextPresentation in '..\library\ui\FHIR.Ui.TextPresentation.pas' {TextPresentationDialog},
  fsl_npm in '..\library\npm\fsl_npm.pas',
  FHIR.Server.IndexingR5 in 'FHIR.Server.IndexingR5.pas',
  FHIR.Server.OperationsR5 in 'FHIR.Server.OperationsR5.pas',
  FHIR.Server.SubscriptionsR5 in 'FHIR.Server.SubscriptionsR5.pas',
  FHIR.Server.ValidatorR5 in 'FHIR.Server.ValidatorR5.pas',
  fhir5_base in '..\library\r5\fhir5_base.pas',
  fhir5_constants in '..\library\r5\fhir5_constants.pas',
  fhir5_enums in '..\library\r5\fhir5_enums.pas',
  fhir5_factory in '..\library\r5\fhir5_factory.pas',
  fhir5_indexinfo in '..\library\r5\fhir5_indexinfo.pas',
  fhir5_json in '..\library\r5\fhir5_json.pas',
  fhir5_pathengine in '..\library\r5\fhir5_pathengine.pas',
  fhir5_pathnode in '..\library\r5\fhir5_pathnode.pas',
  fhir5_profiles in '..\library\r5\fhir5_profiles.pas',
  fhir5_resources in '..\library\r5\fhir5_resources.pas',
  fhir5_tags in '..\library\r5\fhir5_tags.pas',
  fhir5_turtle in '..\library\r5\fhir5_turtle.pas',
  fhir5_types in '..\library\r5\fhir5_types.pas',
  fhir5_utilities in '..\library\r5\fhir5_utilities.pas',
  fhir5_validator in '..\library\r5\fhir5_validator.pas',
  fhir5_xml in '..\library\r5\fhir5_xml.pas',
  fhir5_context in '..\library\r5\fhir5_context.pas',
  fhir5_parserBase in '..\library\r5\fhir5_parserBase.pas',
  fhir5_parser in '..\library\r5\fhir5_parser.pas',
  fhir5_elementmodel in '..\library\r5\fhir5_elementmodel.pas',
  fhir5_common in '..\library\r5\fhir5_common.pas',
  fhir5_opbase in '..\library\r5\fhir5_opbase.pas',
  fhir5_operations in '..\library\r5\fhir5_operations.pas',
  fhir5_authmap in '..\library\r5\fhir5_authmap.pas',
  fhir5_client in '..\library\r5\fhir5_client.pas',
  fhir5_narrative in '..\library\r5\fhir5_narrative.pas',
  fhir5_questionnaire in '..\library\r5\fhir5_questionnaire.pas',
  fhir5_narrative2 in '..\library\r5\fhir5_narrative2.pas',
  fhir5_graphdefinition in '..\library\r5\fhir5_graphdefinition.pas',
  fhir5_maputils in '..\library\r5\fhir5_maputils.pas',
  fsl_npm_spider in '..\library\npm\fsl_npm_spider.pas',
  FHIR.Npm.Manager in '..\library\npm\FHIR.Npm.Manager.pas',
  FHIR.Server.Packages in 'FHIR.Server.Packages.pas',
  fsl_npm_client in '..\library\npm\fsl_npm_client.pas',
  FHIR.Server.Covid in 'Modules\FHIR.Server.Covid.pas',
  fhir4_liquid in '..\library\r4\fhir4_liquid.pas',
  FHIR.Server.Twilio in 'FHIR.Server.Twilio.pas',
  VirtualTrees.AccessibilityFactory in '..\dependencies\treeview\Source\VirtualTrees.AccessibilityFactory.pas',
  VirtualTrees.HeaderPopup in '..\dependencies\treeview\Source\VirtualTrees.HeaderPopup.pas',
  FHIR.Ui.WorkerTask in '..\library\ui\FHIR.Ui.WorkerTask.pas' {WorkingForm},
  FHIR.Npm.VersionBrowser in '..\library\npm\FHIR.Npm.VersionBrowser.pas' {PackageVersionChooserForm},
  FHIR.Server.WebBase in 'FHIR.Server.WebBase.pas',
  FHIR.Server.ClientCacheManager in 'FHIR.Server.ClientCacheManager.pas',
  FHIR.Tx.HGVS in 'FHIR.Tx.HGVS.pas',
  fhir2_resources_canonical in '..\library\r2\fhir2_resources_canonical.pas',
  fhir2_resources_base in '..\library\r2\fhir2_resources_base.pas',
  fhir2_resources_other in '..\library\r2\fhir2_resources_other.pas',
  fhir2_resources_clinical in '..\library\r2\fhir2_resources_clinical.pas',
  fhir2_resources_admin in '..\library\r2\fhir2_resources_admin.pas',
  fhir3_resources_admin in '..\library\r3\fhir3_resources_admin.pas',
  fhir3_resources_other in '..\library\r3\fhir3_resources_other.pas',
  fhir3_resources_clinical in '..\library\r3\fhir3_resources_clinical.pas',
  fhir3_resources_canonical in '..\library\r3\fhir3_resources_canonical.pas',
  fhir3_resources_base in '..\library\r3\fhir3_resources_base.pas',
  fhir4_resources_admin in '..\library\r4\fhir4_resources_admin.pas',
  fhir4_resources_other in '..\library\r4\fhir4_resources_other.pas',
  fhir4_resources_medications in '..\library\r4\fhir4_resources_medications.pas',
  fhir4_resources_financial in '..\library\r4\fhir4_resources_financial.pas',
  fhir4_resources_clinical in '..\library\r4\fhir4_resources_clinical.pas',
  fhir4_resources_canonical in '..\library\r4\fhir4_resources_canonical.pas',
  fhir4_resources_base in '..\library\r4\fhir4_resources_base.pas',
  fhir5_resources_base in '..\library\r5\fhir5_resources_base.pas',
  fhir5_resources_admin in '..\library\r5\fhir5_resources_admin.pas',
  fhir5_resources_canonical in '..\library\r5\fhir5_resources_canonical.pas',
  fhir5_resources_clinical in '..\library\r5\fhir5_resources_clinical.pas',
  fhir5_resources_financial in '..\library\r5\fhir5_resources_financial.pas',
  fhir5_resources_medications in '..\library\r5\fhir5_resources_medications.pas',
  fhir5_resources_other in '..\library\r5\fhir5_resources_other.pas',
  MarkdownUnicodeUtils in '..\..\markdown\source\MarkdownUnicodeUtils.pas',
  FHIR.Server.Telnet in 'FHIR.Server.Telnet.pas',
  FHIR.Server.Kernel.Base in 'FHIR.Server.Kernel.Base.pas',
  FHIR.Server.Kernel.General in 'FHIR.Server.Kernel.General.pas',
  FHIR.Server.Kernel.Bridge in 'FHIR.Server.Kernel.Bridge.pas',
  FHIR.Server.Kernel.Tx in 'FHIR.Server.Kernel.Tx.pas',
  FHIR.Server.Gui.Vcl in 'FHIR.Server.Gui.Vcl.pas' {ServerGUI},
  FHIR.Server.Gui.Controller in 'FHIR.Server.Gui.Controller.pas',
  FHIR.Tools.Search in '..\library\tools\FHIR.Tools.Search.pas',
  FHIR.Server.Operations in 'FHIR.Server.Operations.pas',
  fsl_tests in '..\library\support\fsl_tests.pas',
  fsl_testing in '..\library\support\fsl_testing.pas',
  fsl_comparisons in '..\library\support\fsl_comparisons.pas',
  MarkdownCommonMarkTests in '..\..\markdown\tests\MarkdownCommonMarkTests.pas',
  MarkdownDaringFireballTests in '..\..\markdown\tests\MarkdownDaringFireballTests.pas',
  CommonTestBase in '..\..\markdown\tests\CommonTestBase.pas',
  FHIR.Tx.IETFLang.Tests in 'tests\FHIR.Tx.IETFLang.Tests.pas',
  FHIR.Database.Tests in '..\library\database\FHIR.Database.Tests.pas',
  FHIR.Ucum.Tests in '..\library\Ucum\FHIR.Ucum.Tests.pas',
  dicom_Objects in '..\library\dicom\dicom_Objects.pas',
  dicom_Dictionary in '..\library\dicom\dicom_Dictionary.pas',
  dicom_Writer in '..\library\dicom\dicom_Writer.pas',
  dicom_Parser in '..\library\dicom\dicom_Parser.pas',
  dicom_JpegLS in '..\library\dicom\dicom_JpegLS.pas',
  FHIR.Snomed.Tests in '..\library\snomed\FHIR.Snomed.Tests.pas',
  v2_tests in '..\library\v2\v2_tests.pas',
  v2_base in '..\library\v2\v2_base.pas',
  v2_dictionary in '..\library\v2\v2_dictionary.pas',
  v2_dictionary_Compiled in '..\library\v2\v2_dictionary_Compiled.pas',
  v2_dictionary_v21 in '..\library\v2\v2_dictionary_v21.pas',
  v2_dictionary_v251 in '..\library\v2\v2_dictionary_v251.pas',
  v2_dictionary_v22 in '..\library\v2\v2_dictionary_v22.pas',
  v2_dictionary_v231 in '..\library\v2\v2_dictionary_v231.pas',
  v2_dictionary_v27 in '..\library\v2\v2_dictionary_v27.pas',
  v2_dictionary_v26 in '..\library\v2\v2_dictionary_v26.pas',
  v2_dictionary_v25 in '..\library\v2\v2_dictionary_v25.pas',
  v2_dictionary_v23 in '..\library\v2\v2_dictionary_v23.pas',
  v2_dictionary_v24 in '..\library\v2\v2_dictionary_v24.pas',
  v2_dictionary_Database in '..\library\v2\v2_dictionary_Database.pas',
  v2_objects in '..\library\v2\v2_objects.pas',
  cda_objects in '..\library\cda\cda_objects.pas',
  FHIR.Server.TestRegistry in 'FHIR.Server.TestRegistry.pas',
  cda_documents in '..\library\cda\cda_documents.pas',
  {$IFNDEF NO_JS}
  ChakraDebug in '..\dependencies\chakracore-delphi\ChakraDebug.pas',
  ChakraCoreUtils in '..\dependencies\chakracore-delphi\ChakraCoreUtils.pas',
  ChakraCoreClasses in '..\dependencies\chakracore-delphi\ChakraCoreClasses.pas',
  ChakraCore in '..\dependencies\chakracore-delphi\ChakraCore.pas',
  ChakraCommon in '..\dependencies\chakracore-delphi\ChakraCommon.pas',
  FHIR.Server.EventJs in 'FHIR.Server.EventJs.pas',
  fhir_js_client in '..\library\client\fhir_js_client.pas',
  fhir_javascript in '..\library\javascript\fhir_javascript.pas',
  fhir4_javascript in '..\library\r4\fhir4_javascript.pas',
  FHIR.Server.Javascript in 'FHIR.Server.Javascript.pas',
  fsl_javascript in '..\library\support\fsl_javascript.pas',
  fhir2_javascript in '..\library\r2\fhir2_javascript.pas',
  fhir3_javascript in '..\library\r3\fhir3_javascript.pas',
  v2_javascript in '..\library\v2\v2_javascript.pas',
  fhir5_javascript in '..\library\r5\fhir5_javascript.pas',
  {$ENDIF }
  cda_base in '..\library\cda\cda_base.pas',
  cda_writer in '..\library\cda\cda_writer.pas',
  cda_types in '..\library\cda\cda_types.pas',
  cda_parser in '..\library\cda\cda_parser.pas',
  cda_tests in '..\library\cda\cda_tests.pas',
  FHIR.Server.Kernel.Testing in 'FHIR.Server.Kernel.Testing.pas',
  fsl_tests_web in '..\library\web\fsl_tests_web.pas',
  fhir_tests_javascript in '..\library\javascript\fhir_tests_javascript.pas',
  fhir4_tests_Parser in '..\library\r4\tests\fhir4_tests_Parser.pas',
  fhir4_tests_worker in '..\library\r4\tests\fhir4_tests_worker.pas',
  FHIR.Tx.AreaCode in 'FHIR.Tx.AreaCode.pas',
  fsl_npm_tests in '..\library\npm\fsl_npm_tests.pas',
  fhir4_tests_Context in '..\library\r4\tests\fhir4_tests_Context.pas',
  fsl_tests_scrypt in '..\library\support\fsl_tests_scrypt.pas',
  fhir4_tests_Utilities in '..\library\r4\tests\fhir4_tests_Utilities.pas',
  fhir4_tests_Client in '..\library\r4\tests\fhir4_tests_Client.pas',
  fhir4_tests_Liquid in '..\library\r4\tests\fhir4_tests_Liquid.pas',
  fhir4_tests_PathEngine in '..\library\r4\tests\fhir4_tests_PathEngine.pas';

begin
  ExecuteFhirServer;
end.


