// JCL_DEBUG_EXPERT_INSERTJDBG ON
program FHIRServer;

{
Copyright (c) 2001-2013, Health Intersections Pty Ltd (http://www.healthintersections.com.au)
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of HL7 nor the names of its contributors may be used to
   endorse or promote products derived from this software without specific
   prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
}

{$APPTYPE CONSOLE}

{$R *.res}


{
todo:
STU3 draft:
 - check using UTF-8 in URLs
 - check prepfer = operation outcome
 - check turtle support
 - check versioning in capabilities statement
 - check elements & summary on read/vread
 - check delete return codes
 - changes to id element on update
 - check conditional delete flag.
 - search on multiple resource types
 - check over transaction handling
 - dateTIme parameter on history
 - check use of 401 instead of 403
 - check handling of unsupported parameters
 - check implementations of sa and be prefixes in search
 - review searching on names
 - check search by canonical URL and version
 - add searching for token system|
 - reverse chaining
 - check _list parameter
 - check sorting
 - check handling count = 0
 - composite search parameter work
 - test flag support
 - check document operation
 - check handling binary parameter
 - update FHIR.Version.PathEngine
 - string validation rules
 - Both _include and _revInclude use the wild card "*" for the search parameter name, indicating that any search parameter of type=reference be included.






Add reverse chaining
Grahame, I see you don't respond to either of the following:
 http://hl7connect.healthintersections.com.au/svc/fhir/condition/search?subject=patient/350
 http://hl7connect.healthintersections.com.au/svc/fhir/condition/search?subject=patient/@350
cross resource search
ftx_ucum_base search

}

uses
  FastMM4 in '..\dependencies\FMM\FastMM4.pas',
  FastMM4Messages in '..\dependencies\FMM\FastMM4Messages.pas',
  Windows,
  SysUtils,
  Classes,
  IdSSLOpenSSLHeaders,
  IdCustomHTTPServer,
  MarkdownCommonMark in '..\..\pascal\markdown\source\MarkdownCommonMark.pas',
  MarkdownDaringFireball in '..\..\pascal\markdown\source\MarkdownDaringFireball.pas',
  MarkdownProcessor in '..\..\pascal\markdown\source\MarkdownProcessor.pas',
  fhir_common in '..\library\fhir\fhir_common.pas',
  fhir_factory in '..\library\fhir\fhir_factory.pas',
  fhir_narrative in '..\library\fhir\fhir_narrative.pas',
  fhir_objects in '..\library\fhir\fhir_objects.pas',
  fhir_parser in '..\library\fhir\fhir_parser.pas',
  fhir_pathengine in '..\library\fhir\fhir_pathengine.pas',
  fsl_scim in '..\library\fsl\fsl_scim.pas',
  fhir_utilities in '..\library\fhir\fhir_utilities.pas',
  fhir_validator in '..\library\fhir\fhir_validator.pas',
  fhir_xhtml in '..\library\fhir\fhir_xhtml.pas',
  fsl_npm_cache in '..\library\fsl\fsl_npm_cache.pas',
  cds_hooks_server in 'cds_hooks_server.pas',
  cds_hooks_service in 'cds_hooks_service.pas',
  fhir_cdshooks in '..\library\fhir\fhir_cdshooks.pas',
  fhir_client in '..\library\fhir\fhir_client.pas',
  fhir_client_http in '..\library\fhir\fhir_client_http.pas',
  fhir_client_threaded in '..\library\fhir\fhir_client_threaded.pas',
  fdb_dialects in '..\library\fdb\fdb_dialects.pas',
  fdb_logging in '..\library\fdb\fdb_logging.pas',
  fdb_manager in '..\library\fdb\fdb_manager.pas',
  fdb_odbc in '..\library\fdb\fdb_odbc.pas',
  fdb_odbc_headers in '..\library\fdb\fdb_odbc_headers.pas',
  fdb_odbc_objects in '..\library\fdb\fdb_odbc_objects.pas',
  fdb_sqlite3 in '..\library\fdb\fdb_sqlite3.pas',
  fdb_sqlite3_objects in '..\library\fdb\fdb_sqlite3_objects.pas',
  fdb_sqlite3_utilities in '..\library\fdb\fdb_sqlite3_utilities.pas',
  fdb_sqlite3_wrapper in '..\library\fdb\fdb_sqlite3_wrapper.pas',
  ftx_loinc_importer in '..\library\ftx\ftx_loinc_importer.pas',
  ftx_loinc_publisher in '..\library\ftx\ftx_loinc_publisher.pas',
  ftx_loinc_services in '..\library\ftx\ftx_loinc_services.pas',
  fsl_twilio in '..\library\fsl\fsl_twilio.pas',
  fhir2_base in '..\library\fhir2\fhir2_base.pas',
  fhir2_client in '..\library\fhir2\fhir2_client.pas',
  fhir2_common in '..\library\fhir2\fhir2_common.pas',
  fhir2_constants in '..\library\fhir2\fhir2_constants.pas',
  fhir2_context in '..\library\fhir2\fhir2_context.pas',
  fhir2_elementmodel in '..\library\fhir2\fhir2_elementmodel.pas',
  fhir2_factory in '..\library\fhir2\fhir2_factory.pas',
  fhir2_json in '..\library\fhir2\fhir2_json.pas',
  fhir2_narrative in '..\library\fhir2\fhir2_narrative.pas',
  fhir2_opbase in '..\library\fhir2\fhir2_opbase.pas',
  fhir2_operations in '..\library\fhir2\fhir2_operations.pas',
  fhir2_parser in '..\library\fhir2\fhir2_parser.pas',
  fhir2_parserBase in '..\library\fhir2\fhir2_parserBase.pas',
  fhir2_pathengine in '..\library\fhir2\fhir2_pathengine.pas',
  fhir2_pathnode in '..\library\fhir2\fhir2_pathnode.pas',
  fhir2_profiles in '..\library\fhir2\fhir2_profiles.pas',
  fhir2_resources in '..\library\fhir2\fhir2_resources.pas',
  fhir2_types in '..\library\fhir2\fhir2_types.pas',
  fhir2_utilities in '..\library\fhir2\fhir2_utilities.pas',
  fhir2_validator in '..\library\fhir2\fhir2_validator.pas',
  fhir2_xml in '..\library\fhir2\fhir2_xml.pas',
  fhir3_base in '..\library\fhir3\fhir3_base.pas',
  fhir3_client in '..\library\fhir3\fhir3_client.pas',
  fhir3_common in '..\library\fhir3\fhir3_common.pas',
  fhir3_constants in '..\library\fhir3\fhir3_constants.pas',
  fhir3_context in '..\library\fhir3\fhir3_context.pas',
  fhir3_elementmodel in '..\library\fhir3\fhir3_elementmodel.pas',
  fhir3_factory in '..\library\fhir3\fhir3_factory.pas',
  fhir3_json in '..\library\fhir3\fhir3_json.pas',
  fhir3_narrative in '..\library\fhir3\fhir3_narrative.pas',
  fhir3_opbase in '..\library\fhir3\fhir3_opbase.pas',
  fhir3_operations in '..\library\fhir3\fhir3_operations.pas',
  fhir3_parser in '..\library\fhir3\fhir3_parser.pas',
  fhir3_parserBase in '..\library\fhir3\fhir3_parserBase.pas',
  fhir3_pathengine in '..\library\fhir3\fhir3_pathengine.pas',
  fhir3_pathnode in '..\library\fhir3\fhir3_pathnode.pas',
  fhir3_profiles in '..\library\fhir3\fhir3_profiles.pas',
  fhir3_resources in '..\library\fhir3\fhir3_resources.pas',
  fhir3_turtle in '..\library\fhir3\fhir3_turtle.pas',
  fhir3_types in '..\library\fhir3\fhir3_types.pas',
  fhir3_utilities in '..\library\fhir3\fhir3_utilities.pas',
  fhir3_validator in '..\library\fhir3\fhir3_validator.pas',
  fhir3_xml in '..\library\fhir3\fhir3_xml.pas',
  fhir4_authmap in '..\library\fhir4\fhir4_authmap.pas',
  fhir4_base in '..\library\fhir4\fhir4_base.pas',
  fhir4_client in '..\library\fhir4\fhir4_client.pas',
  fhir4_common in '..\library\fhir4\fhir4_common.pas',
  fhir4_constants in '..\library\fhir4\fhir4_constants.pas',
  fhir4_context in '..\library\fhir4\fhir4_context.pas',
  fhir4_elementmodel in '..\library\fhir4\fhir4_elementmodel.pas',
  fhir4_factory in '..\library\fhir4\fhir4_factory.pas',
  fhir4_indexinfo in '..\library\fhir4\fhir4_indexinfo.pas',
  fhir4_json in '..\library\fhir4\fhir4_json.pas',
  fhir4_maputils in '..\library\fhir4\fhir4_maputils.pas',
  fhir4_narrative in '..\library\fhir4\fhir4_narrative.pas',
  fhir4_narrative2 in '..\library\fhir4\fhir4_narrative2.pas',
  fhir4_opbase in '..\library\fhir4\fhir4_opbase.pas',
  fhir4_operations in '..\library\fhir4\fhir4_operations.pas',
  fhir4_parser in '..\library\fhir4\fhir4_parser.pas',
  fhir4_parserBase in '..\library\fhir4\fhir4_parserBase.pas',
  fhir4_pathengine in '..\library\fhir4\fhir4_pathengine.pas',
  fhir4_pathnode in '..\library\fhir4\fhir4_pathnode.pas',
  fhir4_profiles in '..\library\fhir4\fhir4_profiles.pas',
  fhir4_questionnaire in '..\library\fhir4\fhir4_questionnaire.pas',
  fhir4_resources in '..\library\fhir4\fhir4_resources.pas',
  fhir4_turtle in '..\library\fhir4\fhir4_turtle.pas',
  fhir4_types in '..\library\fhir4\fhir4_types.pas',
  fhir4_utilities in '..\library\fhir4\fhir4_utilities.pas',
  fhir4_validator in '..\library\fhir4\fhir4_validator.pas',
  fhir4_xml in '..\library\fhir4\fhir4_xml.pas',
  scim_search in 'scim_search.pas',
  scim_server in 'scim_server.pas',
  accesscontrol in 'accesscontrol.pas',
  auth_manager in 'auth_manager.pas',
  closuremanager in 'closuremanager.pas',
  server_constants in 'server_constants.pas',
  database_installer in 'database_installer.pas',
  database in 'database.pas',
  graph_definition in 'graph_definition.pas',
  jwt in 'jwt.pas',
  kernel in 'kernel.pas',
  mpi_search in 'mpi_search.pas',
  obsservation_stats in 'obsservation_stats.pas',
  reverse_client in 'reverse_client.pas',
  search in 'search.pas',
  search_syntax in 'search_syntax.pas',
  security in '..\library\tools\security.pas',
  session in '..\library\tools\session.pas',
  storage in 'storage.pas',
  subscriptions in 'subscriptions.pas',
  user_manager in 'user_manager.pas',
  utilities in 'utilities.pas',
  web_server in 'web_server.pas',
  web_source in 'web_source.pas',
  html_builder in 'html_builder.pas',
  fhir_oauth in '..\library\fhir\fhir_oauth.pas',
  ftx_sct_analysis in '..\library\ftx\ftx_sct_analysis.pas',
  ftx_sct_expressions in '..\library\ftx\ftx_sct_expressions.pas',
  ftx_sct_importer in '..\library\ftx\ftx_sct_importer.pas',
  ftx_sct_publisher in '..\library\ftx\ftx_sct_publisher.pas',
  ftx_sct_services in '..\library\ftx\ftx_sct_services.pas',
  fsl_base in '..\library\fsl\fsl_base.pas',
  fsl_crypto in '..\library\fsl\fsl_crypto.pas',
  fsl_collections in '..\library\fsl\fsl_collections.pas',
  fsl_fpc in '..\library\fsl\fsl_fpc.pas',
  fsl_json in '..\library\fsl\fsl_json.pas',
  fsl_logging in '..\library\fsl\fsl_logging.pas',
  fsl_xml in '..\library\fsl\fsl_xml.pas',
  fsl_msxml in '..\library\fsl\fsl_msxml.pas',
  fsl_service_win in '..\library\fsl\fsl_service_win.pas',
  fsl_shell in '..\library\fsl\fsl_shell.pas',
  fsl_openssl in '..\library\fsl\fsl_openssl.pas',
  fsl_stream in '..\library\fsl\fsl_stream.pas',
  fsl_threads in '..\library\fsl\fsl_threads.pas',
  fsl_turtle in '..\library\fsl\fsl_turtle.pas',
  fsl_utilities in '..\library\fsl\fsl_utilities.pas',
  fhir_codegen in '..\library\fhir\fhir_codegen.pas',
  fhir_diff in '..\library\fhir\fhir_diff.pas',
  fhir_graphql in '..\library\fhir\fhir_graphql.pas',
  fhir_indexing in '..\library\fhir\fhir_indexing.pas',
  tx_acir in 'tx_acir.pas',
  tx_countrycode in 'tx_countrycode.pas',
  tx_iso_4217 in 'tx_iso_4217.pas',
  ftx_lang in '..\library\ftx\ftx_lang.pas',
  tx_manager in 'tx_manager.pas',
  tx_mimetypes in 'tx_mimetypes.pas',
  tx_operations in 'tx_operations.pas',
  tx_rxnorm in 'tx_rxnorm.pas',
  tx_server in 'tx_server.pas',
  ftx_service in '..\library\ftx\ftx_service.pas',
  tx_unii in 'tx_unii.pas',
  tx_uri in 'tx_uri.pas',
  tx_us_states in 'tx_us_states.pas',
  tx_webserver in 'tx_webserver.pas',
  ftx_ucum_base in '..\library\ftx\ftx_ucum_base.pas',
  ftx_ucum_expressions in '..\library\ftx\ftx_ucum_expressions.pas',
  ftx_ucum_handlers in '..\library\ftx\ftx_ucum_handlers.pas',
  fsl_ucum in '..\library\fsl\fsl_ucum.pas',
  ftx_ucum_search in '..\library\ftx\ftx_ucum_search.pas',
  ftx_ucum_services in '..\library\ftx\ftx_ucum_services.pas',
  ftx_ucum_validators in '..\library\ftx\ftx_ucum_validators.pas',
  fsl_scrypt in '..\library\fsl\fsl_scrypt.pas',
  fsl_oauth in '..\library\fsl\fsl_oauth.pas',
  fsl_fetcher in '..\library\fsl\fsl_fetcher.pas',
  fsl_graphql in '..\library\fsl\fsl_graphql.pas',
  fsl_htmlgen in '..\library\fsl\fsl_htmlgen.pas',
  fsl_http in '..\library\fsl\fsl_http.pas',
  fsl_rdf in '..\library\fsl\fsl_rdf.pas',
  fsl_websocket in '..\library\fsl\fsl_websocket.pas',
  fsl_wininet in '..\library\fsl\fsl_wininet.pas',
  fxver_convertor_base in '..\library\fxver\fxver_convertor_base.pas',
  tags in 'tags.pas',
  fhir_codesystem_service in '..\library\ftx\fhir_codesystem_service.pas',
  fhir_valuesets in '..\library\ftx\fhir_valuesets.pas',
  server_context in 'server_context.pas',
  indexing in 'indexing.pas',
  fhir2_indexinfo in '..\library\fhir2\fhir2_indexinfo.pas',
  fhir3_indexinfo in '..\library\fhir3\fhir3_indexinfo.pas',
  fhir2_authmap in '..\library\fhir2\fhir2_authmap.pas',
  fhir3_authmap in '..\library\fhir3\fhir3_authmap.pas',
  fhir4_graphdefinition in '..\library\fhir4\fhir4_graphdefinition.pas',
  fhir_graphdefinition in '..\library\fhir\fhir_graphdefinition.pas',
  bundlebuilder in 'bundlebuilder.pas',
  indexing_r4 in 'indexing_r4.pas',
  indexing_r3 in 'indexing_r3.pas',
  indexing_r2 in 'indexing_r2.pas',
  operations_r2 in 'operations_r2.pas',
  operations_r3 in 'operations_r3.pas',
  operations_r4 in 'operations_r4.pas',
  subscriptions_r2 in 'subscriptions_r2.pas',
  subscriptions_r3 in 'subscriptions_r3.pas',
  subscriptions_r4 in 'subscriptions_r4.pas',
  fhir2_questionnaire in '..\library\fhir2\fhir2_questionnaire.pas',
  fhir2_narrative2 in '..\library\fhir2\fhir2_narrative2.pas',
  fhir3_questionnaire in '..\library\fhir3\fhir3_questionnaire.pas',
  fhir3_narrative2 in '..\library\fhir3\fhir3_narrative2.pas',
  fxver_convertors in '..\library\fxver\fxver_convertors.pas',
  fxver_convertor_30_40 in '..\library\fxver\fxver_convertor_30_40.pas',
  fhir_ndjson in '..\library\fhir\fhir_ndjson.pas',
  server_factory in 'server_factory.pas',
  validator_r4 in 'validator_r4.pas',
  validator_r2 in 'validator_r2.pas',
  validator_r3 in 'validator_r3.pas',
  session_manager in 'session_manager.pas',
  VirtualTrees.Actions in '..\dependencies\treeview\Source\VirtualTrees.Actions.pas',
  VirtualTrees.Classes in '..\dependencies\treeview\Source\VirtualTrees.Classes.pas',
  VirtualTrees.ClipBoard in '..\dependencies\treeview\Source\VirtualTrees.ClipBoard.pas',
  VirtualTrees.Export in '..\dependencies\treeview\Source\VirtualTrees.Export.pas',
  VirtualTrees in '..\dependencies\treeview\Source\VirtualTrees.pas',
  VirtualTrees.StyleHooks in '..\dependencies\treeview\Source\VirtualTrees.StyleHooks.pas',
  VirtualTrees.Utils in '..\dependencies\treeview\Source\VirtualTrees.Utils.pas',
  VirtualTrees.WorkerThread in '..\dependencies\treeview\Source\VirtualTrees.WorkerThread.pas',
  VTAccessibility in '..\dependencies\treeview\Source\VTAccessibility.pas',
  VTAccessibilityFactory in '..\dependencies\treeview\Source\VTAccessibilityFactory.pas',
  VTHeaderPopup in '..\dependencies\treeview\Source\VTHeaderPopup.pas',
  ftx_sct_combiner in '..\library\ftx\ftx_sct_combiner.pas',
  fsl_lang in '..\library\fsl\fsl_lang.pas',
  JclDebug in '..\dependencies\jcl\JclDebug.pas',
  JclBase in '..\dependencies\jcl\JclBase.pas',
  JclResources in '..\dependencies\jcl\JclResources.pas',
  JclFileUtils in '..\dependencies\jcl\JclFileUtils.pas',
  JclWin32 in '..\dependencies\jcl\JclWin32.pas',
  JclSysUtils in '..\dependencies\jcl\JclSysUtils.pas',
  JclSynch in '..\dependencies\jcl\JclSynch.pas',
  JclLogic in '..\dependencies\jcl\JclLogic.pas',
  JclRegistry in '..\dependencies\jcl\JclRegistry.pas',
  JclStrings in '..\dependencies\jcl\JclStrings.pas',
  JclAnsiStrings in '..\dependencies\jcl\JclAnsiStrings.pas',
  JclStreams in '..\dependencies\jcl\JclStreams.pas',
  JclStringConversions in '..\dependencies\jcl\JclStringConversions.pas',
  JclCharsets in '..\dependencies\jcl\JclCharsets.pas',
  JclMath in '..\dependencies\jcl\JclMath.pas',
  Jcl8087 in '..\dependencies\jcl\Jcl8087.pas',
  JclConsole in '..\dependencies\jcl\JclConsole.pas',
  JclShell in '..\dependencies\jcl\JclShell.pas',
  JclWideStrings in '..\dependencies\jcl\JclWideStrings.pas',
  JclUnicode in '..\dependencies\jcl\JclUnicode.pas',
  JclSysInfo in '..\dependencies\jcl\JclSysInfo.pas',
  Snmp in '..\dependencies\jcl\Snmp.pas',
  JclIniFiles in '..\dependencies\jcl\JclIniFiles.pas',
  JclSecurity in '..\dependencies\jcl\JclSecurity.pas',
  JclDateTime in '..\dependencies\jcl\JclDateTime.pas',
  JclPeImage in '..\dependencies\jcl\JclPeImage.pas',
  JclTD32 in '..\dependencies\jcl\JclTD32.pas',
  JclHookExcept in '..\dependencies\jcl\JclHookExcept.pas',
  v2_server in 'v2_server.pas',
  v2_protocol in '..\library\v2\v2_protocol.pas',
  v2_message in '..\library\v2\v2_message.pas',
  cda_narrative in '..\library\cda\cda_narrative.pas',
  fhir_oids in '..\library\fhir\fhir_oids.pas',
  fhir_elementmodel in '..\library\fhir\fhir_elementmodel.pas',
  Compat in '..\dependencies\chakracore-delphi\Compat.pas',
  MarkdownHTMLEntities in '..\..\pascal\markdown\source\MarkdownHTMLEntities.pas',
  consent_engine in 'consent_engine.pas',
  tx_ndc in 'tx_ndc.pas',
  fsl_npm in '..\library\fsl\fsl_npm.pas',
  indexing_r5 in 'indexing_r5.pas',
  operations_r5 in 'operations_r5.pas',
  subscriptions_r5 in 'subscriptions_r5.pas',
  validator_r5 in 'validator_r5.pas',
  fhir5_base in '..\library\fhir5\fhir5_base.pas',
  fhir5_constants in '..\library\fhir5\fhir5_constants.pas',
  fhir5_enums in '..\library\fhir5\fhir5_enums.pas',
  fhir5_factory in '..\library\fhir5\fhir5_factory.pas',
  fhir5_indexinfo in '..\library\fhir5\fhir5_indexinfo.pas',
  fhir5_json in '..\library\fhir5\fhir5_json.pas',
  fhir5_pathengine in '..\library\fhir5\fhir5_pathengine.pas',
  fhir5_pathnode in '..\library\fhir5\fhir5_pathnode.pas',
  fhir5_profiles in '..\library\fhir5\fhir5_profiles.pas',
  fhir5_resources in '..\library\fhir5\fhir5_resources.pas',
  fhir5_tags in '..\library\fhir5\fhir5_tags.pas',
  fhir5_turtle in '..\library\fhir5\fhir5_turtle.pas',
  fhir5_types in '..\library\fhir5\fhir5_types.pas',
  fhir5_utilities in '..\library\fhir5\fhir5_utilities.pas',
  fhir5_validator in '..\library\fhir5\fhir5_validator.pas',
  fhir5_xml in '..\library\fhir5\fhir5_xml.pas',
  fhir5_context in '..\library\fhir5\fhir5_context.pas',
  fhir5_parserBase in '..\library\fhir5\fhir5_parserBase.pas',
  fhir5_parser in '..\library\fhir5\fhir5_parser.pas',
  fhir5_elementmodel in '..\library\fhir5\fhir5_elementmodel.pas',
  fhir5_common in '..\library\fhir5\fhir5_common.pas',
  fhir5_opbase in '..\library\fhir5\fhir5_opbase.pas',
  fhir5_operations in '..\library\fhir5\fhir5_operations.pas',
  fhir5_authmap in '..\library\fhir5\fhir5_authmap.pas',
  fhir5_client in '..\library\fhir5\fhir5_client.pas',
  fhir5_narrative in '..\library\fhir5\fhir5_narrative.pas',
  fhir5_questionnaire in '..\library\fhir5\fhir5_questionnaire.pas',
  fhir5_narrative2 in '..\library\fhir5\fhir5_narrative2.pas',
  fhir5_graphdefinition in '..\library\fhir5\fhir5_graphdefinition.pas',
  fhir5_maputils in '..\library\fhir5\fhir5_maputils.pas',
  package_spider in 'package_spider.pas',
  fsl_npm_client in '..\library\fsl\fsl_npm_client.pas',
  fhir4_liquid in '..\library\fhir4\fhir4_liquid.pas',
  twilio in 'twilio.pas',
  VirtualTrees.AccessibilityFactory in '..\dependencies\treeview\Source\VirtualTrees.AccessibilityFactory.pas',
  VirtualTrees.HeaderPopup in '..\dependencies\treeview\Source\VirtualTrees.HeaderPopup.pas',
  web_base in 'web_base.pas',
  client_cache_manager in 'client_cache_manager.pas',
  tx_hgvs in 'tx_hgvs.pas',
  fhir2_resources_canonical in '..\library\fhir2\fhir2_resources_canonical.pas',
  fhir2_resources_base in '..\library\fhir2\fhir2_resources_base.pas',
  fhir2_resources_other in '..\library\fhir2\fhir2_resources_other.pas',
  fhir2_resources_clinical in '..\library\fhir2\fhir2_resources_clinical.pas',
  fhir2_resources_admin in '..\library\fhir2\fhir2_resources_admin.pas',
  fhir3_resources_admin in '..\library\fhir3\fhir3_resources_admin.pas',
  fhir3_resources_other in '..\library\fhir3\fhir3_resources_other.pas',
  fhir3_resources_clinical in '..\library\fhir3\fhir3_resources_clinical.pas',
  fhir3_resources_canonical in '..\library\fhir3\fhir3_resources_canonical.pas',
  fhir3_resources_base in '..\library\fhir3\fhir3_resources_base.pas',
  fhir4_resources_admin in '..\library\fhir4\fhir4_resources_admin.pas',
  fhir4_resources_other in '..\library\fhir4\fhir4_resources_other.pas',
  fhir4_resources_medications in '..\library\fhir4\fhir4_resources_medications.pas',
  fhir4_resources_financial in '..\library\fhir4\fhir4_resources_financial.pas',
  fhir4_resources_clinical in '..\library\fhir4\fhir4_resources_clinical.pas',
  fhir4_resources_canonical in '..\library\fhir4\fhir4_resources_canonical.pas',
  fhir4_resources_base in '..\library\fhir4\fhir4_resources_base.pas',
  fhir5_resources_base in '..\library\fhir5\fhir5_resources_base.pas',
  fhir5_resources_admin in '..\library\fhir5\fhir5_resources_admin.pas',
  fhir5_resources_canonical in '..\library\fhir5\fhir5_resources_canonical.pas',
  fhir5_resources_clinical in '..\library\fhir5\fhir5_resources_clinical.pas',
  fhir5_resources_financial in '..\library\fhir5\fhir5_resources_financial.pas',
  fhir5_resources_medications in '..\library\fhir5\fhir5_resources_medications.pas',
  fhir5_resources_other in '..\library\fhir5\fhir5_resources_other.pas',
  MarkdownUnicodeUtils in '..\..\pascal\markdown\source\MarkdownUnicodeUtils.pas',
  telnet_server in 'telnet_server.pas',
  gui_vcl in 'gui_vcl.pas' {ServerGUI},
  gui_controller in 'gui_controller.pas',
  search_base in '..\library\tools\search_base.pas',
  operations in 'operations.pas',
  fsl_tests in '..\library\fsl\tests\fsl_tests.pas',
  fsl_testing in '..\library\fsl\tests\fsl_testing.pas',
  fsl_comparisons in '..\library\fsl\fsl_comparisons.pas',
  MarkdownCommonMarkTests in '..\..\pascal\markdown\tests\MarkdownCommonMarkTests.pas',
  MarkdownDaringFireballTests in '..\..\pascal\markdown\tests\MarkdownDaringFireballTests.pas',
  CommonTestBase in '..\..\pascal\markdown\tests\CommonTestBase.pas',
  ftx_tests_lang in '..\library\ftx\tests\ftx_tests_lang.pas',
  ftx_tests_ucum in '..\library\ftx\tests\ftx_tests_ucum.pas',
  dicom_Objects in '..\library\dicom\dicom_Objects.pas',
  dicom_Dictionary in '..\library\dicom\dicom_Dictionary.pas',
  dicom_Writer in '..\library\dicom\dicom_Writer.pas',
  dicom_Parser in '..\library\dicom\dicom_Parser.pas',
  dicom_JpegLS in '..\library\dicom\dicom_JpegLS.pas',
  ftx_tests_sct in '..\library\ftx\tests\ftx_tests_sct.pas',
  v2_tests in '..\library\v2\tests\v2_tests.pas',
  v2_base in '..\library\v2\v2_base.pas',
  v2_dictionary in '..\library\v2\v2_dictionary.pas',
  v2_dictionary_Compiled in '..\library\v2\v2_dictionary_Compiled.pas',
  v2_dictionary_v21 in '..\library\v2\v2_dictionary_v21.pas',
  v2_dictionary_v251 in '..\library\v2\v2_dictionary_v251.pas',
  v2_dictionary_v22 in '..\library\v2\v2_dictionary_v22.pas',
  v2_dictionary_v231 in '..\library\v2\v2_dictionary_v231.pas',
  v2_dictionary_v27 in '..\library\v2\v2_dictionary_v27.pas',
  v2_dictionary_v26 in '..\library\v2\v2_dictionary_v26.pas',
  v2_dictionary_v25 in '..\library\v2\v2_dictionary_v25.pas',
  v2_dictionary_v23 in '..\library\v2\v2_dictionary_v23.pas',
  v2_dictionary_v24 in '..\library\v2\v2_dictionary_v24.pas',
  v2_dictionary_Database in '..\library\v2\v2_dictionary_Database.pas',
  v2_objects in '..\library\v2\v2_objects.pas',
  cda_objects in '..\library\cda\cda_objects.pas',
  test_registry in 'test_registry.pas',
  cda_documents in '..\library\cda\cda_documents.pas',
  {$IFNDEF NO_JS}
  ChakraDebug in '..\dependencies\chakracore-delphi\ChakraDebug.pas',
  ChakraCoreUtils in '..\dependencies\chakracore-delphi\ChakraCoreUtils.pas',
  ChakraCoreClasses in '..\dependencies\chakracore-delphi\ChakraCoreClasses.pas',
  ChakraCore in '..\dependencies\chakracore-delphi\ChakraCore.pas',
  ChakraCommon in '..\dependencies\chakracore-delphi\ChakraCommon.pas',
  event_js in 'event_js.pas',
  fhir_js_client in '..\library\fhir\fhir_js_client.pas',
  fhir_javascript in '..\library\fhir\fhir_javascript.pas',
  fhir4_javascript in '..\library\fhir4\fhir4_javascript.pas',
  server_javascript in 'server_javascript.pas',
  fsl_javascript in '..\library\fsl\fsl_javascript.pas',
  fhir2_javascript in '..\library\fhir2\fhir2_javascript.pas',
  fhir3_javascript in '..\library\fhir3\fhir3_javascript.pas',
  v2_javascript in '..\library\v2\v2_javascript.pas',
  fhir5_javascript in '..\library\fhir5\fhir5_javascript.pas',
  {$ENDIF }
  cda_base in '..\library\cda\cda_base.pas',
  cda_writer in '..\library\cda\cda_writer.pas',
  cda_types in '..\library\cda\cda_types.pas',
  cda_parser in '..\library\cda\cda_parser.pas',
  cda_tests in '..\library\cda\tests\cda_tests.pas',
  fdb_tests in '..\library\fdb\tests\fdb_tests.pas',
  server_testing in 'server_testing.pas',
  fsl_tests_web in '..\library\fsl\tests\fsl_tests_web.pas',
  fhir_tests_javascript in '..\library\fhir\tests\fhir_tests_javascript.pas',
  fhir4_tests_Parser in '..\library\fhir4\tests\fhir4_tests_Parser.pas',
  fhir4_tests_worker in '..\library\fhir4\tests\fhir4_tests_worker.pas',
  tx_areacode in 'tx_areacode.pas',
  fsl_tests_npm in '..\library\fsl\tests\fsl_tests_npm.pas',
  fhir4_tests_Context in '..\library\fhir4\tests\fhir4_tests_Context.pas',
  fsl_tests_scrypt in '..\library\fsl\tests\fsl_tests_scrypt.pas',
  fhir4_tests_Utilities in '..\library\fhir4\tests\fhir4_tests_Utilities.pas',
  fhir4_tests_Client in '..\library\fhir4\tests\fhir4_tests_Client.pas',
  fhir4_tests_Liquid in '..\library\fhir4\tests\fhir4_tests_Liquid.pas',
  fhir4_tests_PathEngine in '..\library\fhir4\tests\fhir4_tests_PathEngine.pas',
  fxver_tests in '..\library\fxver\tests\fxver_tests.pas',
  fsl_tests_iduri in '..\library\fsl\tests\fsl_tests_iduri.pas',
  tests_search_syntax in 'tests\tests_search_syntax.pas',
  fhir4_tests_graphql in '..\library\fhir4\tests\fhir4_tests_graphql.pas',
  server_config in 'admin\server_config.pas',
  test_server_config in 'tests\test_server_config.pas',
  web_event in 'web_event.pas',
  endpoint_snomed in 'endpoint_snomed.pas',
  endpoint_twilio in 'endpoint_twilio.pas',
  endpoint_packages in 'endpoint_packages.pas',
  endpoint_storage in 'endpoint_storage.pas',
  endpoint_loinc in 'endpoint_loinc.pas',
  internal_client in 'internal_client.pas',
  endpoint_bridge in 'endpoint_bridge.pas',
  endpoint_txsvr in 'endpoint_txsvr.pas',
  endpoint_full in 'endpoint_full.pas',
  endpoint in 'endpoint.pas',
  web_cache in 'web_cache.pas',
  fsl_diff in '..\library\fsl\fsl_diff.pas';

begin
  ExecuteFhirServer;
end.


