type
  REFGUID = tGUID;                                  //updt 090812 not sure
  REFIID =  pGUID;                                  //updt 090812 not sure, REFIID in Direct3d replaced by pGUID
  CLSID =  tCLSID;                                  //updt 090812 in ActiveX
  REFCLSID = ^tCLSID;                             //updt 090812 in Direct3d
  REFPROPVARIANT = tPropVariant;                    //updt 090812 pretty sure of this one
  PUINT32 = ^Uint32;                                //updt 090812
