program FHIRToolkit;

uses
  FastMM4 in '..\Libraries\FMM\FastMM4.pas',
  System.StartUpCopy,
  FMX.Forms,
  FHIRClient in '..\reference-platform\dstu3\FHIRClient.pas',
  StringSupport in '..\reference-platform\support\StringSupport.pas',
  MathSupport in '..\reference-platform\support\MathSupport.pas',
  EncodeSupport in '..\reference-platform\support\EncodeSupport.pas',
  GUIDSupport in '..\reference-platform\support\GUIDSupport.pas',
  OSXUtils in '..\reference-platform\support\OSXUtils.pas',
  DecimalSupport in '..\reference-platform\support\DecimalSupport.pas',
  DateSupport in '..\reference-platform\support\DateSupport.pas',
  MimeMessage in '..\reference-platform\support\MimeMessage.pas',
  AdvObjects in '..\reference-platform\support\AdvObjects.pas',
  AdvExceptions in '..\reference-platform\support\AdvExceptions.pas',
  AdvGenerics in '..\reference-platform\support\AdvGenerics.pas',
  AdvStreams in '..\reference-platform\support\AdvStreams.pas',
  AdvObjectLists in '..\reference-platform\support\AdvObjectLists.pas',
  MemorySupport in '..\reference-platform\support\MemorySupport.pas',
  AdvItems in '..\reference-platform\support\AdvItems.pas',
  AdvFilers in '..\reference-platform\support\AdvFilers.pas',
  ColourSupport in '..\reference-platform\support\ColourSupport.pas',
  CurrencySupport in '..\reference-platform\support\CurrencySupport.pas',
  AdvCollections in '..\reference-platform\support\AdvCollections.pas',
  AdvPersistents in '..\reference-platform\support\AdvPersistents.pas',
  AdvIterators in '..\reference-platform\support\AdvIterators.pas',
  AdvMemories in '..\reference-platform\support\AdvMemories.pas',
  AdvBuffers in '..\reference-platform\support\AdvBuffers.pas',
  BytesSupport in '..\reference-platform\support\BytesSupport.pas',
  AdvStringBuilders in '..\reference-platform\support\AdvStringBuilders.pas',
  FileSupport in '..\reference-platform\support\FileSupport.pas',
  AdvPersistentLists in '..\reference-platform\support\AdvPersistentLists.pas',
  AdvFiles in '..\reference-platform\support\AdvFiles.pas',
  ErrorSupport in '..\reference-platform\support\ErrorSupport.pas',
  AdvStringMatches in '..\reference-platform\support\AdvStringMatches.pas',
  AdvJSON in '..\reference-platform\support\AdvJSON.pas',
  AdvVCLStreams in '..\reference-platform\support\AdvVCLStreams.pas',
  AdvTextFormatters in '..\reference-platform\support\AdvTextFormatters.pas',
  AdvFormatters in '..\reference-platform\support\AdvFormatters.pas',
  AdvTextExtractors in '..\reference-platform\support\AdvTextExtractors.pas',
  AdvExtractors in '..\reference-platform\support\AdvExtractors.pas',
  AdvCharacterSets in '..\reference-platform\support\AdvCharacterSets.pas',
  AdvOrdinalSets in '..\reference-platform\support\AdvOrdinalSets.pas',
  AdvStringLists in '..\reference-platform\support\AdvStringLists.pas',
  AdvCSVFormatters in '..\reference-platform\support\AdvCSVFormatters.pas',
  AdvCSVExtractors in '..\reference-platform\support\AdvCSVExtractors.pas',
  AdvStreamReaders in '..\reference-platform\support\AdvStreamReaders.pas',
  AdvStringStreams in '..\reference-platform\support\AdvStringStreams.pas',
  TextUtilities in '..\reference-platform\support\TextUtilities.pas',
  ParserSupport in '..\reference-platform\support\ParserSupport.pas',
  FHIRParser in '..\reference-platform\support\FHIRParser.pas',
  FHIRParserXml in '..\reference-platform\dstu3\FHIRParserXml.pas',
  FHIRParserBase in '..\reference-platform\support\FHIRParserBase.pas',
  MXML in '..\reference-platform\support\MXML.pas',
  XMLBuilder in '..\reference-platform\support\XMLBuilder.pas',
  MXmlBuilder in '..\reference-platform\support\MXmlBuilder.pas',
  AdvXmlBuilders in '..\reference-platform\support\AdvXmlBuilders.pas',
  AdvXMLFormatters in '..\reference-platform\support\AdvXMLFormatters.pas',
  AdvXMLEntities in '..\reference-platform\support\AdvXMLEntities.pas',
  TurtleParser in '..\reference-platform\support\TurtleParser.pas',
  FHIRBase in '..\reference-platform\support\FHIRBase.pas',
  AdvNames in '..\reference-platform\support\AdvNames.pas',
  FHIRUtilities in '..\reference-platform\dstu3\FHIRUtilities.pas',
  OIDSupport in '..\reference-platform\support\OIDSupport.pas',
  ParseMap in '..\reference-platform\support\ParseMap.pas',
  AdvZipWriters in '..\reference-platform\support\AdvZipWriters.pas',
  AdvZipDeclarations in '..\reference-platform\support\AdvZipDeclarations.pas',
  AdvZipParts in '..\reference-platform\support\AdvZipParts.pas',
  AdvZipUtilities in '..\reference-platform\support\AdvZipUtilities.pas',
  AdvZipWorkers in '..\reference-platform\support\AdvZipWorkers.pas',
  AdvNameBuffers in '..\reference-platform\support\AdvNameBuffers.pas',
  AdvObjectMatches in '..\reference-platform\support\AdvObjectMatches.pas',
  InternetFetcher in '..\reference-platform\support\InternetFetcher.pas',
  FHIRContext in '..\reference-platform\dstu3\FHIRContext.pas',
  FHIRTypes in '..\reference-platform\dstu3\FHIRTypes.pas',
  FHIRResources in '..\reference-platform\dstu3\FHIRResources.pas',
  FHIRSupport in '..\reference-platform\dstu3\FHIRSupport.pas',
  JWT in '..\reference-platform\support\JWT.pas',
  HMAC in '..\reference-platform\support\HMAC.pas',
  libeay32 in '..\reference-platform\support\libeay32.pas',
  SCIMObjects in '..\reference-platform\support\SCIMObjects.pas',
  GraphQL in '..\reference-platform\support\GraphQL.pas',
  FHIRConstants in '..\reference-platform\dstu3\FHIRConstants.pas',
  FHIRSecurity in '..\reference-platform\support\FHIRSecurity.pas',
  FHIRTags in '..\reference-platform\dstu3\FHIRTags.pas',
  FHIRLang in '..\reference-platform\support\FHIRLang.pas',
  FHIRXhtml in '..\reference-platform\support\FHIRXhtml.pas',
  FHIRParserJson in '..\reference-platform\dstu3\FHIRParserJson.pas',
  FHIRParserTurtle in '..\reference-platform\dstu3\FHIRParserTurtle.pas',
  FHIRMetaModel in '..\reference-platform\dstu3\FHIRMetaModel.pas',
  FHIRProfileUtilities in '..\reference-platform\dstu3\FHIRProfileUtilities.pas',
  kCritSct in '..\reference-platform\support\kCritSct.pas',
  AdvZipReaders in '..\reference-platform\support\AdvZipReaders.pas',
  FhirPath in '..\reference-platform\dstu3\FhirPath.pas',
  SystemSupport in '..\reference-platform\support\SystemSupport.pas',
  ThreadSupport in '..\reference-platform\support\ThreadSupport.pas',
  SmartOnFhirUtilities in '..\reference-platform\support\SmartOnFhirUtilities.pas',
  MarkdownProcessor in '..\..\markdown\source\MarkdownProcessor.pas',
  MarkdownDaringFireball in '..\..\markdown\source\MarkdownDaringFireball.pas',
  MarkdownCommonMark in '..\..\markdown\source\MarkdownCommonMark.pas',
  HashSupport in '..\reference-platform\support\HashSupport.pas',
  CDSHooksUtilities in '..\reference-platform\support\CDSHooksUtilities.pas',
  {$IFNDEF OSX}
  AfsStreamManagers in '..\reference-platform\support\AfsStreamManagers.pas',
  AfsVolumes in '..\reference-platform\support\AfsVolumes.pas',
  AfsResourceVolumes in '..\reference-platform\support\AfsResourceVolumes.pas',
  AdvWinInetClients in '..\reference-platform\support\AdvWinInetClients.pas',
  {$ENDIF }
  AdvStringHashes in '..\reference-platform\support\AdvStringHashes.pas',
  AdvHashes in '..\reference-platform\support\AdvHashes.pas',
  FastMM4Messages in '..\Libraries\FMM\FastMM4Messages.pas',
  OrganizationChooser in 'OrganizationChooser.pas' {OrganizationSelectionForm},
  FHIRToolkitForm in 'FHIRToolkitForm.pas' {MasterToolsForm},
  ServerForm in 'ServerForm.pas' {ServerFrameForm: TFrame},
  AppEndorserFrame in 'AppEndorserFrame.pas' {AppEndorsementFrame: TFrame},
  BaseFrame in 'BaseFrame.pas',
  ValueSetEditor in 'ValueSetEditor.pas' {ValueSetEditorFrame: TFrame},
  SearchParameterEditor in 'SearchParameterEditor.pas' {SearchParameterEditorForm},
  ListSelector in 'ListSelector.pas' {ListSelectorForm},
  FHIRIndexInformation in '..\reference-platform\dstu3\FHIRIndexInformation.pas',
  FHIRIndexBase in '..\reference-platform\support\FHIRIndexBase.pas',
  AddRestResourceDialog in 'AddRestResourceDialog.pas' {AddRestResourceForm},
  SourceViewer in 'SourceViewer.pas' {SourceViewerForm},
  DifferenceEngine in '..\reference-platform\support\DifferenceEngine.pas',
  BaseResourceFrame in 'BaseResourceFrame.pas',
  BaseServerFrame in 'BaseServerFrame.pas',
  CapabilityStatementEditor in 'CapabilityStatementEditor.pas' {CapabilityStatementEditorFrame: TFrame},
  ValuesetExpansion in 'ValuesetExpansion.pas' {ValuesetExpansionForm},
  HelpContexts in 'HelpContexts.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TMasterToolsForm, MasterToolsForm);
  Application.CreateForm(TOrganizationSelectionForm, OrganizationSelectionForm);
  Application.CreateForm(TSearchParameterEditorForm, SearchParameterEditorForm);
  Application.CreateForm(TListSelectorForm, ListSelectorForm);
  Application.CreateForm(TAddRestResourceForm, AddRestResourceForm);
  Application.CreateForm(TSourceViewerForm, SourceViewerForm);
  Application.CreateForm(TValuesetExpansionForm, ValuesetExpansionForm);
  Application.Run;
end.
