CREATE TABLE [dbo].[AreaCodes](
	[Display] [nchar](255) NOT NULL,
	[Code] [nchar](10) NOT NULL,
	[Abbrev] [nchar](255) NOT NULL,
 CONSTRAINT [PK_AreaCodes] PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

Go
insert into AreaCodes (Code, Display, Abbrev) values ('004', 'Afghanistan', 'AFG')
insert into AreaCodes (Code, Display, Abbrev) values ('248', 'Åland Islands', 'ALA')
insert into AreaCodes (Code, Display, Abbrev) values ('008', 'Albania', 'ALB')
insert into AreaCodes (Code, Display, Abbrev) values ('012', 'Algeria', 'DZA')
insert into AreaCodes (Code, Display, Abbrev) values ('016', 'American Samoa', 'ASM')
insert into AreaCodes (Code, Display, Abbrev) values ('020', 'Andorra', 'AND')
insert into AreaCodes (Code, Display, Abbrev) values ('024', 'Angola', 'AGO')
insert into AreaCodes (Code, Display, Abbrev) values ('660', 'Anguilla', 'AIA')
insert into AreaCodes (Code, Display, Abbrev) values ('028', 'Antigua and Barbuda', 'ATG')
insert into AreaCodes (Code, Display, Abbrev) values ('032', 'Argentina', 'ARG')
insert into AreaCodes (Code, Display, Abbrev) values ('051', 'Armenia', 'ARM')
insert into AreaCodes (Code, Display, Abbrev) values ('533', 'Aruba', 'ABW')
insert into AreaCodes (Code, Display, Abbrev) values ('036', 'Australia', 'AUS')
insert into AreaCodes (Code, Display, Abbrev) values ('040', 'Austria', 'AUT')
insert into AreaCodes (Code, Display, Abbrev) values ('031', 'Azerbaijan', 'AZE')
insert into AreaCodes (Code, Display, Abbrev) values ('044', 'Bahamas', 'BHS')
insert into AreaCodes (Code, Display, Abbrev) values ('048', 'Bahrain', 'BHR')
insert into AreaCodes (Code, Display, Abbrev) values ('050', 'Bangladesh', 'BGD')
insert into AreaCodes (Code, Display, Abbrev) values ('052', 'Barbados', 'BRB')
insert into AreaCodes (Code, Display, Abbrev) values ('112', 'Belarus', 'BLR')
insert into AreaCodes (Code, Display, Abbrev) values ('056', 'Belgium', 'BEL')
insert into AreaCodes (Code, Display, Abbrev) values ('084', 'Belize', 'BLZ')
insert into AreaCodes (Code, Display, Abbrev) values ('204', 'Benin', 'BEN')
insert into AreaCodes (Code, Display, Abbrev) values ('060', 'Bermuda', 'BMU')
insert into AreaCodes (Code, Display, Abbrev) values ('064', 'Bhutan', 'BTN')
insert into AreaCodes (Code, Display, Abbrev) values ('068', 'Bolivia (Plurinational State of)', 'BOL')
insert into AreaCodes (Code, Display, Abbrev) values ('535', 'Bonaire, Sint Eustatius and Saba', 'BES')
insert into AreaCodes (Code, Display, Abbrev) values ('070', 'Bosnia and Herzegovina', 'BIH')
insert into AreaCodes (Code, Display, Abbrev) values ('072', 'Botswana', 'BWA')
insert into AreaCodes (Code, Display, Abbrev) values ('076', 'Brazil', 'BRA')
insert into AreaCodes (Code, Display, Abbrev) values ('092', 'British Virgin Islands', 'VGB')
insert into AreaCodes (Code, Display, Abbrev) values ('096', 'Brunei Darussalam', 'BRN')
insert into AreaCodes (Code, Display, Abbrev) values ('100', 'Bulgaria', 'BGR')
insert into AreaCodes (Code, Display, Abbrev) values ('854', 'Burkina Faso', 'BFA')
insert into AreaCodes (Code, Display, Abbrev) values ('108', 'Burundi', 'BDI')
insert into AreaCodes (Code, Display, Abbrev) values ('132', 'Cabo Verde', 'CPV')
insert into AreaCodes (Code, Display, Abbrev) values ('116', 'Cambodia', 'KHM')
insert into AreaCodes (Code, Display, Abbrev) values ('120', 'Cameroon', 'CMR')
insert into AreaCodes (Code, Display, Abbrev) values ('124', 'Canada', 'CAN')
insert into AreaCodes (Code, Display, Abbrev) values ('136', 'Cayman Islands', 'CYM')
insert into AreaCodes (Code, Display, Abbrev) values ('140', 'Central African Republic', 'CAF')
insert into AreaCodes (Code, Display, Abbrev) values ('148', 'Chad', 'TCD')
insert into AreaCodes (Code, Display, Abbrev) values ('830', 'Channel Islands	', '')
insert into AreaCodes (Code, Display, Abbrev) values ('152', 'Chile', 'CHL')
insert into AreaCodes (Code, Display, Abbrev) values ('156', 'China', 'CHN')
insert into AreaCodes (Code, Display, Abbrev) values ('344', 'China, Hong Kong Special Administrative Region', 'HKG')
insert into AreaCodes (Code, Display, Abbrev) values ('446', 'China, Macao Special Administrative Region', 'MAC')
insert into AreaCodes (Code, Display, Abbrev) values ('170', 'Colombia', 'COL')
insert into AreaCodes (Code, Display, Abbrev) values ('174', 'Comoros', 'COM')
insert into AreaCodes (Code, Display, Abbrev) values ('178', 'Congo', 'COG')
insert into AreaCodes (Code, Display, Abbrev) values ('184', 'Cook Islands', 'COK')
insert into AreaCodes (Code, Display, Abbrev) values ('188', 'Costa Rica', 'CRI')
insert into AreaCodes (Code, Display, Abbrev) values ('384', 'Côte d''Ivoire', 'CIV')
insert into AreaCodes (Code, Display, Abbrev) values ('191', 'Croatia', 'HRV')
insert into AreaCodes (Code, Display, Abbrev) values ('192', 'Cuba', 'CUB')
insert into AreaCodes (Code, Display, Abbrev) values ('531', 'Curaçao', 'CUW')
insert into AreaCodes (Code, Display, Abbrev) values ('196', 'Cyprus', 'CYP')
insert into AreaCodes (Code, Display, Abbrev) values ('203', 'Czech Republic', 'CZE')
insert into AreaCodes (Code, Display, Abbrev) values ('408', 'Democratic People''s Republic of Korea', 'PRK')
insert into AreaCodes (Code, Display, Abbrev) values ('180', 'Democratic Republic of the Congo', 'COD')
insert into AreaCodes (Code, Display, Abbrev) values ('208', 'Denmark', 'DNK')
insert into AreaCodes (Code, Display, Abbrev) values ('262', 'Djibouti', 'DJI')
insert into AreaCodes (Code, Display, Abbrev) values ('212', 'Dominica', 'DMA')
insert into AreaCodes (Code, Display, Abbrev) values ('214', 'Dominican Republic', 'DOM')
insert into AreaCodes (Code, Display, Abbrev) values ('218', 'Ecuador', 'ECU')
insert into AreaCodes (Code, Display, Abbrev) values ('818', 'Egypt', 'EGY')
insert into AreaCodes (Code, Display, Abbrev) values ('222', 'El Salvador', 'SLV')
insert into AreaCodes (Code, Display, Abbrev) values ('226', 'Equatorial Guinea', 'GNQ')
insert into AreaCodes (Code, Display, Abbrev) values ('232', 'Eritrea', 'ERI')
insert into AreaCodes (Code, Display, Abbrev) values ('233', 'Estonia', 'EST')
insert into AreaCodes (Code, Display, Abbrev) values ('231', 'Ethiopia', 'ETH')
insert into AreaCodes (Code, Display, Abbrev) values ('234', 'Faeroe Islands', 'FRO')
insert into AreaCodes (Code, Display, Abbrev) values ('238', 'Falkland Islands (Malvinas)', 'FLK')
insert into AreaCodes (Code, Display, Abbrev) values ('242', 'Fiji', 'FJI')
insert into AreaCodes (Code, Display, Abbrev) values ('246', 'Finland', 'FIN')
insert into AreaCodes (Code, Display, Abbrev) values ('250', 'France', 'FRA')
insert into AreaCodes (Code, Display, Abbrev) values ('254', 'French Guiana', 'GUF')
insert into AreaCodes (Code, Display, Abbrev) values ('258', 'French Polynesia', 'PYF')
insert into AreaCodes (Code, Display, Abbrev) values ('266', 'Gabon', 'GAB')
insert into AreaCodes (Code, Display, Abbrev) values ('270', 'Gambia', 'GMB')
insert into AreaCodes (Code, Display, Abbrev) values ('268', 'Georgia', 'GEO')
insert into AreaCodes (Code, Display, Abbrev) values ('276', 'Germany', 'DEU')
insert into AreaCodes (Code, Display, Abbrev) values ('288', 'Ghana', 'GHA')
insert into AreaCodes (Code, Display, Abbrev) values ('292', 'Gibraltar', 'GIB')
insert into AreaCodes (Code, Display, Abbrev) values ('300', 'Greece', 'GRC')
insert into AreaCodes (Code, Display, Abbrev) values ('304', 'Greenland', 'GRL')
insert into AreaCodes (Code, Display, Abbrev) values ('308', 'Grenada', 'GRD')
insert into AreaCodes (Code, Display, Abbrev) values ('312', 'Guadeloupe', 'GLP')
insert into AreaCodes (Code, Display, Abbrev) values ('316', 'Guam', 'GUM')
insert into AreaCodes (Code, Display, Abbrev) values ('320', 'Guatemala', 'GTM')
insert into AreaCodes (Code, Display, Abbrev) values ('831', 'Guernsey', 'GGY')
insert into AreaCodes (Code, Display, Abbrev) values ('324', 'Guinea', 'GIN')
insert into AreaCodes (Code, Display, Abbrev) values ('624', 'Guinea-Bissau', 'GNB')
insert into AreaCodes (Code, Display, Abbrev) values ('328', 'Guyana', 'GUY')
insert into AreaCodes (Code, Display, Abbrev) values ('332', 'Haiti', 'HTI')
insert into AreaCodes (Code, Display, Abbrev) values ('336', 'Holy See', 'VAT')
insert into AreaCodes (Code, Display, Abbrev) values ('340', 'Honduras', 'HND')
insert into AreaCodes (Code, Display, Abbrev) values ('348', 'Hungary', 'HUN')
insert into AreaCodes (Code, Display, Abbrev) values ('352', 'Iceland', 'ISL')
insert into AreaCodes (Code, Display, Abbrev) values ('356', 'India', 'IND')
insert into AreaCodes (Code, Display, Abbrev) values ('360', 'Indonesia', 'IDN')
insert into AreaCodes (Code, Display, Abbrev) values ('364', 'Iran (Islamic Republic of)', 'IRN')
insert into AreaCodes (Code, Display, Abbrev) values ('368', 'Iraq', 'IRQ')
insert into AreaCodes (Code, Display, Abbrev) values ('372', 'Ireland', 'IRL')
insert into AreaCodes (Code, Display, Abbrev) values ('833', 'Isle of Man', 'IMN')
insert into AreaCodes (Code, Display, Abbrev) values ('376', 'Israel', 'ISR')
insert into AreaCodes (Code, Display, Abbrev) values ('380', 'Italy', 'ITA')
insert into AreaCodes (Code, Display, Abbrev) values ('388', 'Jamaica', 'JAM')
insert into AreaCodes (Code, Display, Abbrev) values ('392', 'Japan', 'JPN')
insert into AreaCodes (Code, Display, Abbrev) values ('832', 'Jersey	JEY', '')
insert into AreaCodes (Code, Display, Abbrev) values ('400', 'Jordan', 'JOR')
insert into AreaCodes (Code, Display, Abbrev) values ('398', 'Kazakhstan', 'KAZ')
insert into AreaCodes (Code, Display, Abbrev) values ('404', 'Kenya', 'KEN')
insert into AreaCodes (Code, Display, Abbrev) values ('296', 'Kiribati', 'KIR')
insert into AreaCodes (Code, Display, Abbrev) values ('414', 'Kuwait', 'KWT')
insert into AreaCodes (Code, Display, Abbrev) values ('417', 'Kyrgyzstan', 'KGZ')
insert into AreaCodes (Code, Display, Abbrev) values ('418', 'Lao People''s Democratic Republic', 'LAO')
insert into AreaCodes (Code, Display, Abbrev) values ('428', 'Latvia', 'LVA')
insert into AreaCodes (Code, Display, Abbrev) values ('422', 'Lebanon', 'LBN')
insert into AreaCodes (Code, Display, Abbrev) values ('426', 'Lesotho', 'LSO')
insert into AreaCodes (Code, Display, Abbrev) values ('430', 'Liberia', 'LBR')
insert into AreaCodes (Code, Display, Abbrev) values ('434', 'Libya', 'LBY')
insert into AreaCodes (Code, Display, Abbrev) values ('438', 'Liechtenstein', 'LIE')
insert into AreaCodes (Code, Display, Abbrev) values ('440', 'Lithuania', 'LTU')
insert into AreaCodes (Code, Display, Abbrev) values ('442', 'Luxembourg', 'LUX')
insert into AreaCodes (Code, Display, Abbrev) values ('450', 'Madagascar', 'MDG')
insert into AreaCodes (Code, Display, Abbrev) values ('454', 'Malawi', 'MWI')
insert into AreaCodes (Code, Display, Abbrev) values ('458', 'Malaysia', 'MYS')
insert into AreaCodes (Code, Display, Abbrev) values ('462', 'Maldives', 'MDV')
insert into AreaCodes (Code, Display, Abbrev) values ('466', 'Mali', 'MLI')
insert into AreaCodes (Code, Display, Abbrev) values ('470', 'Malta', 'MLT')
insert into AreaCodes (Code, Display, Abbrev) values ('584', 'Marshall Islands', 'MHL')
insert into AreaCodes (Code, Display, Abbrev) values ('474', 'Martinique', 'MTQ')
insert into AreaCodes (Code, Display, Abbrev) values ('478', 'Mauritania', 'MRT')
insert into AreaCodes (Code, Display, Abbrev) values ('480', 'Mauritius', 'MUS')
insert into AreaCodes (Code, Display, Abbrev) values ('175', 'Mayotte	MYT', '')
insert into AreaCodes (Code, Display, Abbrev) values ('484', 'Mexico', 'MEX')
insert into AreaCodes (Code, Display, Abbrev) values ('583', 'Micronesia (Federated States of)', 'FSM')
insert into AreaCodes (Code, Display, Abbrev) values ('492', 'Monaco', 'MCO')
insert into AreaCodes (Code, Display, Abbrev) values ('496', 'Mongolia', 'MNG')
insert into AreaCodes (Code, Display, Abbrev) values ('499', 'Montenegro', 'MNE')
insert into AreaCodes (Code, Display, Abbrev) values ('500', 'Montserrat', 'MSR')
insert into AreaCodes (Code, Display, Abbrev) values ('504', 'Morocco', 'MAR')
insert into AreaCodes (Code, Display, Abbrev) values ('508', 'Mozambique', 'MOZ')
insert into AreaCodes (Code, Display, Abbrev) values ('104', 'Myanmar', 'MMR')
insert into AreaCodes (Code, Display, Abbrev) values ('516', 'Namibia', 'NAM')
insert into AreaCodes (Code, Display, Abbrev) values ('520', 'Nauru', 'NRU')
insert into AreaCodes (Code, Display, Abbrev) values ('524', 'Nepal', 'NPL')
insert into AreaCodes (Code, Display, Abbrev) values ('528', 'Netherlands', 'NLD')
insert into AreaCodes (Code, Display, Abbrev) values ('540', 'New Caledonia', 'NCL')
insert into AreaCodes (Code, Display, Abbrev) values ('554', 'New Zealand', 'NZL')
insert into AreaCodes (Code, Display, Abbrev) values ('558', 'Nicaragua', 'NIC')
insert into AreaCodes (Code, Display, Abbrev) values ('562', 'Niger', 'NER')
insert into AreaCodes (Code, Display, Abbrev) values ('566', 'Nigeria', 'NGA')
insert into AreaCodes (Code, Display, Abbrev) values ('570', 'Niue', 'NIU')
insert into AreaCodes (Code, Display, Abbrev) values ('574', 'Norfolk Island', 'NFK')
insert into AreaCodes (Code, Display, Abbrev) values ('580', 'Northern Mariana Islands', 'MNP')
insert into AreaCodes (Code, Display, Abbrev) values ('578', 'Norway', 'NOR')
insert into AreaCodes (Code, Display, Abbrev) values ('512', 'Oman', 'OMN')
insert into AreaCodes (Code, Display, Abbrev) values ('586', 'Pakistan', 'PAK')
insert into AreaCodes (Code, Display, Abbrev) values ('585', 'Palau', 'PLW')
insert into AreaCodes (Code, Display, Abbrev) values ('591', 'Panama', 'PAN')
insert into AreaCodes (Code, Display, Abbrev) values ('598', 'Papua New Guinea', 'PNG')
insert into AreaCodes (Code, Display, Abbrev) values ('600', 'Paraguay', 'PRY')
insert into AreaCodes (Code, Display, Abbrev) values ('604', 'Peru', 'PER')
insert into AreaCodes (Code, Display, Abbrev) values ('608', 'Philippines', 'PHL')
insert into AreaCodes (Code, Display, Abbrev) values ('612', 'Pitcairn', 'PCN')
insert into AreaCodes (Code, Display, Abbrev) values ('616', 'Poland', 'POL')
insert into AreaCodes (Code, Display, Abbrev) values ('620', 'Portugal', 'PRT')
insert into AreaCodes (Code, Display, Abbrev) values ('630', 'Puerto Rico', 'PRI')
insert into AreaCodes (Code, Display, Abbrev) values ('634', 'Qatar', 'QAT')
insert into AreaCodes (Code, Display, Abbrev) values ('410', 'Republic of Korea', 'KOR')
insert into AreaCodes (Code, Display, Abbrev) values ('498', 'Republic of Moldova', 'MDA')
insert into AreaCodes (Code, Display, Abbrev) values ('638', 'Réunion', 'REU')
insert into AreaCodes (Code, Display, Abbrev) values ('642', 'Romania', 'ROU')
insert into AreaCodes (Code, Display, Abbrev) values ('643', 'Russian Federation', 'RUS')
insert into AreaCodes (Code, Display, Abbrev) values ('646', 'Rwanda', 'RWA')
insert into AreaCodes (Code, Display, Abbrev) values ('652', 'Saint Barthélemy', 'BLM')
insert into AreaCodes (Code, Display, Abbrev) values ('654', 'Saint Helena', 'SHN')
insert into AreaCodes (Code, Display, Abbrev) values ('659', 'Saint Kitts and Nevis', 'KNA')
insert into AreaCodes (Code, Display, Abbrev) values ('662', 'Saint Lucia', 'LCA')
insert into AreaCodes (Code, Display, Abbrev) values ('663', 'Saint Martin (French part)	MAF', '')
insert into AreaCodes (Code, Display, Abbrev) values ('666', 'Saint Pierre and Miquelon', 'SPM')
insert into AreaCodes (Code, Display, Abbrev) values ('670', 'Saint Vincent and the Grenadines', 'VCT')
insert into AreaCodes (Code, Display, Abbrev) values ('882', 'Samoa', 'WSM')
insert into AreaCodes (Code, Display, Abbrev) values ('674', 'San Marino', 'SMR')
insert into AreaCodes (Code, Display, Abbrev) values ('678', 'Sao Tome and Principe', 'STP')
insert into AreaCodes (Code, Display, Abbrev) values ('680', 'Sark', ' ')
insert into AreaCodes (Code, Display, Abbrev) values ('682', 'Saudi Arabia', 'SAU')
insert into AreaCodes (Code, Display, Abbrev) values ('686', 'Senegal', 'SEN')
insert into AreaCodes (Code, Display, Abbrev) values ('688', 'Serbia', 'SRB')
insert into AreaCodes (Code, Display, Abbrev) values ('690', 'Seychelles', 'SYC')
insert into AreaCodes (Code, Display, Abbrev) values ('694', 'Sierra Leone', 'SLE')
insert into AreaCodes (Code, Display, Abbrev) values ('702', 'Singapore', 'SGP')
insert into AreaCodes (Code, Display, Abbrev) values ('534', 'Sint Maarten (Dutch part)	SXM', '')
insert into AreaCodes (Code, Display, Abbrev) values ('703', 'Slovakia', 'SVK')
insert into AreaCodes (Code, Display, Abbrev) values ('705', 'Slovenia', 'SVN')
insert into AreaCodes (Code, Display, Abbrev) values ('090', 'Solomon Islands', 'SLB')
insert into AreaCodes (Code, Display, Abbrev) values ('706', 'Somalia', 'SOM')
insert into AreaCodes (Code, Display, Abbrev) values ('710', 'South Africa', 'ZAF')
insert into AreaCodes (Code, Display, Abbrev) values ('728', 'South Sudan', 'SSD')
insert into AreaCodes (Code, Display, Abbrev) values ('724', 'Spain', 'ESP')
insert into AreaCodes (Code, Display, Abbrev) values ('144', 'Sri Lanka', 'LKA')
insert into AreaCodes (Code, Display, Abbrev) values ('275', 'State of Palestine', 'PSE')
insert into AreaCodes (Code, Display, Abbrev) values ('729', 'Sudan', 'SDN')
insert into AreaCodes (Code, Display, Abbrev) values ('740', 'Suriname', 'SUR')
insert into AreaCodes (Code, Display, Abbrev) values ('744', 'Svalbard and Jan Mayen Islands', 'SJM')
insert into AreaCodes (Code, Display, Abbrev) values ('748', 'Swaziland', 'SWZ')
insert into AreaCodes (Code, Display, Abbrev) values ('752', 'Sweden', 'SWE')
insert into AreaCodes (Code, Display, Abbrev) values ('756', 'Switzerland', 'CHE')
insert into AreaCodes (Code, Display, Abbrev) values ('760', 'Syrian Arab Republic', 'SYR')
insert into AreaCodes (Code, Display, Abbrev) values ('762', 'Tajikistan', 'TJK')
insert into AreaCodes (Code, Display, Abbrev) values ('764', 'Thailand', 'THA')
insert into AreaCodes (Code, Display, Abbrev) values ('807', 'The former Yugoslav Republic of Macedonia', 'MKD')
insert into AreaCodes (Code, Display, Abbrev) values ('626', 'Timor-Leste', 'TLS')
insert into AreaCodes (Code, Display, Abbrev) values ('768', 'Togo', 'TGO')
insert into AreaCodes (Code, Display, Abbrev) values ('772', 'Tokelau', 'TKL')
insert into AreaCodes (Code, Display, Abbrev) values ('776', 'Tonga', 'TON')
insert into AreaCodes (Code, Display, Abbrev) values ('780', 'Trinidad and Tobago', 'TTO')
insert into AreaCodes (Code, Display, Abbrev) values ('788', 'Tunisia', 'TUN')
insert into AreaCodes (Code, Display, Abbrev) values ('792', 'Turkey', 'TUR')
insert into AreaCodes (Code, Display, Abbrev) values ('795', 'Turkmenistan', 'TKM')
insert into AreaCodes (Code, Display, Abbrev) values ('796', 'Turks and Caicos Islands', 'TCA')
insert into AreaCodes (Code, Display, Abbrev) values ('798', 'Tuvalu', 'TUV')
insert into AreaCodes (Code, Display, Abbrev) values ('800', 'Uganda', 'UGA')
insert into AreaCodes (Code, Display, Abbrev) values ('804', 'Ukraine', 'UKR')
insert into AreaCodes (Code, Display, Abbrev) values ('784', 'United Arab Emirates', 'ARE')
insert into AreaCodes (Code, Display, Abbrev) values ('826', 'United Kingdom of Great Britain and Northern Ireland', 'GBR')
insert into AreaCodes (Code, Display, Abbrev) values ('834', 'United Republic of Tanzania', 'TZA')
insert into AreaCodes (Code, Display, Abbrev) values ('840', 'United States of America', 'USA')
insert into AreaCodes (Code, Display, Abbrev) values ('850', 'United States Virgin Islands', 'VIR')
insert into AreaCodes (Code, Display, Abbrev) values ('858', 'Uruguay', 'URY')
insert into AreaCodes (Code, Display, Abbrev) values ('860', 'Uzbekistan', 'UZB')
insert into AreaCodes (Code, Display, Abbrev) values ('548', 'Vanuatu', 'VUT')
insert into AreaCodes (Code, Display, Abbrev) values ('862', 'Venezuela (Bolivarian Republic of)', 'VEN')
insert into AreaCodes (Code, Display, Abbrev) values ('704', 'Viet Nam', 'VNM')
insert into AreaCodes (Code, Display, Abbrev) values ('876', 'Wallis and Futuna Islands', 'WLF')
insert into AreaCodes (Code, Display, Abbrev) values ('732', 'Western Sahara', 'ESH')
insert into AreaCodes (Code, Display, Abbrev) values ('887', 'Yemen', 'YEM')
insert into AreaCodes (Code, Display, Abbrev) values ('894', 'Zambia', 'ZMB')
insert into AreaCodes (Code, Display, Abbrev) values ('716', 'Zimbabwe', 'ZWE')
