CREATE TABLE [dbo].[CountryCodes](
	[Display] [nchar](255) NOT NULL,
	[Code] [nchar](10) NOT NULL,
	[Status] [nchar](255) NOT NULL,
 CONSTRAINT [PK_CountryCodes] PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

Go
insert into CountryCodes (display, code, status) values ('USSR', 'SU', 'Exceptionally reserved')
insert into CountryCodes (display, code, status) values ('United States Miscellaneous Pacific Islands', 'PU', 'Formerly used')
insert into CountryCodes (display, code, status) values ('New Hebrides', 'NH', 'Formerly used')
insert into CountryCodes (display, code, status) values ('Johnston Island', 'JT', 'Formerly used')
insert into CountryCodes (display, code, status) values ('Dronning Maud Land', 'NQ', 'Formerly used')
insert into CountryCodes (display, code, status) values ('Wake Island', 'WK', 'Formerly used')
insert into CountryCodes (display, code, status) values ('Panama Canal Zone', 'PZ', 'Formerly used')
insert into CountryCodes (display, code, status) values ('Midway Islands', 'MI', 'Formerly used')
insert into CountryCodes (display, code, status) values ('Yemen, Democratic', 'YD', 'Formerly used')
insert into CountryCodes (display, code, status) values ('Dahomey', 'DY', 'Formerly used')
insert into CountryCodes (display, code, status) values ('Southern Rhodesia', 'RH', 'Formerly used')
insert into CountryCodes (display, code, status) values ('Canton and Enderbury Islands', 'CT', 'Formerly used')
insert into CountryCodes (display, code, status) values ('Viet-Nam, Democratic Republic of', 'VD', 'Formerly used')
insert into CountryCodes (display, code, status) values ('French Southern and Antarctic Territories', 'FQ', 'Formerly used')
insert into CountryCodes (display, code, status) values ('German Democratic Republic', 'DD', 'Formerly used')
insert into CountryCodes (display, code, status) values ('Pacific Islands (Trust Territory)', 'PC', 'Formerly used')
insert into CountryCodes (display, code, status) values ('Upper Volta', 'HV', 'Formerly used')
insert into CountryCodes (display, code, status) values ('Australia', 'AU', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Côte d''Ivoire', 'CI', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Nepal', 'NP', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Jordan', 'JO', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Algeria', 'DZ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Saint Lucia', 'LC', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Bermuda', 'BM', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Slovenia', 'SI', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Malta', 'MT', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Iceland', 'IS', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Kyrgyzstan', 'KG', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Tanzania, United Republic of', 'TZ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Eritrea', 'ER', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Viet Nam', 'VN', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('French Guiana', 'GF', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Paraguay', 'PY', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Antarctica', 'AQ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Netherlands (the)', 'NL', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Fiji', 'FJ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Wallis and Futuna', 'WF', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Burundi', 'BI', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Sweden', 'SE', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Northern Mariana Islands (the)', 'MP', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('British Indian Ocean Territory (the)', 'IO', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Czech Republic (the)', 'CZ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Tuvalu', 'TV', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('United Kingdom of Great Britain and Northern Ireland (the)', 'GB', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Armenia', 'AM', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Canada', 'CA', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Lithuania', 'LT', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Swaziland', 'SZ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Belgium', 'BE', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Saudi Arabia', 'SA', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Mali', 'ML', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Guinea-Bissau', 'GW', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Cabo Verde', 'CV', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Turkey', 'TR', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Anguilla', 'AI', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Réunion', 'RE', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Belize', 'BZ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('El Salvador', 'SV', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Bosnia and Herzegovina', 'BA', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Marshall Islands (the)', 'MH', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('South Georgia and the South Sandwich Islands', 'GS', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Costa Rica', 'CR', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Tunisia', 'TN', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Saint Pierre and Miquelon', 'PM', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('United Arab Emirates (the)', 'AE', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Samoa', 'WS', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Hong Kong', 'HK', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Bouvet Island', 'BV', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Suriname', 'SR', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Djibouti', 'DJ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Korea (the Democratic People''s Republic of)', 'KP', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Moldova (the Republic of)', 'MD', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Azerbaijan', 'AZ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('China', 'CN', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Tajikistan', 'TJ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Niue', 'NU', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Brazil', 'BR', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Senegal', 'SN', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Malaysia', 'MY', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Oman', 'OM', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Qatar', 'QA', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('French Southern Territories (the)', 'TF', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Peru', 'PE', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Japan', 'JP', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Faroe Islands (the)', 'FO', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Brunei Darussalam', 'BN', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Svalbard and Jan Mayen', 'SJ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Mauritius', 'MU', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Italy', 'IT', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Cambodia', 'KH', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Spain', 'ES', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Guernsey', 'GG', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Argentina', 'AR', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Central African Republic (the)', 'CF', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Libya', 'LY', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Panama', 'PA', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Mayotte', 'YT', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('United States of America (the)', 'US', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Falkland Islands (the) [Malvinas]', 'FK', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Benin', 'BJ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Martinique', 'MQ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Taiwan (Province of China)', 'TW', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Luxembourg', 'LU', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Nicaragua', 'NI', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Haiti', 'HT', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Burkina Faso', 'BF', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Cayman Islands (the)', 'KY', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Solomon Islands', 'SB', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Myanmar', 'MM', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Israel', 'IL', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Curaçao', 'CW', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Virgin Islands (British)', 'VG', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Puerto Rico', 'PR', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Niger (the)', 'NE', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Dominican Republic (the)', 'DO', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Barbados', 'BB', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Guatemala', 'GT', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Tonga', 'TO', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Egypt', 'EG', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('New Zealand', 'NZ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Saint Vincent and the Grenadines', 'VC', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Pitcairn', 'PN', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Afghanistan', 'AF', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Namibia', 'NA', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Botswana', 'BW', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('South Sudan', 'SS', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Denmark', 'DK', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Uganda', 'UG', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Montenegro', 'ME', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Guadeloupe', 'GP', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Indonesia', 'ID', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Rwanda', 'RW', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Colombia', 'CO', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Tokelau', 'TK', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Ecuador', 'EC', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Liechtenstein', 'LI', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Bahamas (the)', 'BS', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Somalia', 'SO', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Mozambique', 'MZ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Comoros (the)', 'KM', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Morocco', 'MA', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Greenland', 'GL', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Aruba', 'AW', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Serbia', 'RS', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Cook Islands (the)', 'CK', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Togo', 'TG', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Nauru', 'NR', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('French Polynesia', 'PF', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Bolivia (Plurinational State of)', 'BO', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Slovakia', 'SK', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Maldives', 'MV', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Kiribati', 'KI', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Ethiopia', 'ET', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Ghana', 'GH', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('American Samoa', 'AS', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Romania', 'RO', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Congo (the)', 'CG', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Turks and Caicos Islands (the)', 'TC', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Jamaica', 'JM', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Lao People''s Democratic Republic (the)', 'LA', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Singapore', 'SG', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Mauritania', 'MR', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Iraq', 'IQ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Zambia', 'ZM', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Kenya', 'KE', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Grenada', 'GD', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Palau', 'PW', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Angola', 'AO', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Cocos (Keeling) Islands (the)', 'CC', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Latvia', 'LV', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Hungary', 'HU', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Bulgaria', 'BG', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Kazakhstan', 'KZ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Seychelles', 'SC', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Mongolia', 'MN', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Guyana', 'GY', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Isle of Man', 'IM', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Christmas Island', 'CX', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Trinidad and Tobago', 'TT', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Palestine, State of', 'PS', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Liberia', 'LR', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Norfolk Island', 'NF', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Jersey', 'JE', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Sint Maarten (Dutch part)', 'SX', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Guam', 'GU', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Western Sahara*', 'EH', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Antigua and Barbuda', 'AG', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Heard Island and McDonald Islands', 'HM', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Sao Tome and Principe', 'ST', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Korea (the Republic of)', 'KR', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Saint Martin (French part)', 'MF', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Equatorial Guinea', 'GQ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Ireland', 'IE', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('South Africa', 'ZA', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Timor-Leste', 'TL', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Pakistan', 'PK', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Bhutan', 'BT', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Yemen', 'YE', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Saint Kitts and Nevis', 'KN', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Vanuatu', 'VU', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Gambia (the)', 'GM', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Åland Islands', 'AX', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Chile', 'CL', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Thailand', 'TH', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Papua New Guinea', 'PG', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Uruguay', 'UY', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Sierra Leone', 'SL', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Malawi', 'MW', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Gibraltar', 'GI', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Austria', 'AT', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Switzerland', 'CH', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Chad', 'TD', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Norway', 'NO', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Lebanon', 'LB', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Micronesia (Federated States of)', 'FM', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Saint Barthélemy', 'BL', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Montserrat', 'MS', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Iran (Islamic Republic of)', 'IR', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Georgia', 'GE', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Congo (the Democratic Republic of the)', 'CD', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Finland', 'FI', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Bahrain', 'BH', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Sudan (the)', 'SD', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Macao', 'MO', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('India', 'IN', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Cyprus', 'CY', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Virgin Islands (U.S.)', 'VI', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Gabon', 'GA', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Portugal', 'PT', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Albania', 'AL', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Lesotho', 'LS', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Nigeria', 'NG', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Croatia', 'HR', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Syrian Arab Republic', 'SY', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('United States Minor Outlying Islands (the)', 'UM', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Bangladesh', 'BD', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Kuwait', 'KW', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Macedonia (the former Yugoslav Republic of)', 'MK', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Cuba', 'CU', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Venezuela (Bolivarian Republic of)', 'VE', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('New Caledonia', 'NC', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Honduras', 'HN', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Belarus', 'BY', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Dominica', 'DM', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Madagascar', 'MG', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Greece', 'GR', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Turkmenistan', 'TM', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Estonia', 'EE', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Holy See (the)', 'VA', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Poland', 'PL', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Andorra', 'AD', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Sri Lanka', 'LK', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Zimbabwe', 'ZW', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Monaco', 'MC', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Guinea', 'GN', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Russian Federation (the)', 'RU', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Cameroon', 'CM', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Philippines (the)', 'PH', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Uzbekistan', 'UZ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('France', 'FR', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Bonaire, Sint Eustatius and Saba', 'BQ', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('San Marino', 'SM', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Germany', 'DE', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Mexico', 'MX', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Ukraine', 'UA', 'Officially assigned')
insert into CountryCodes (display, code, status) values ('Netherlands Antilles', 'AN', 'Transitionally reserved')
insert into CountryCodes (display, code, status) values ('Serbia and Montenegro', 'CS', 'Transitionally reserved')
insert into CountryCodes (display, code, status) values ('Yugoslavia', 'YU', 'Transitionally reserved')
insert into CountryCodes (display, code, status) values ('East Timor', 'TP', 'Transitionally reserved')
insert into CountryCodes (display, code, status) values ('Zaire', 'ZR', 'Transitionally reserved')
insert into CountryCodes (display, code, status) values ('Burma', 'BU', 'Transitionally reserved')
insert into CountryCodes (display, code, status) values ('Neutral Zone', 'NT', 'Transitionally reserved')
