Program ClinicalDocumentEditor;

uses
  FastMM4 in '..\..\dependencies\FMM\FastMM4.pas',
  Forms,
  CDEForm in 'CDEForm.pas' {TWordProcessorForm},
  FastMM4Messages in '..\..\dependencies\FMM\FastMM4Messages.pas',
  DropBMPTarget in '..\..\dependencies\ui\DropBMPTarget.pas',
  DropSource in '..\..\dependencies\ui\DropSource.pas',
  DropTarget in '..\..\dependencies\ui\DropTarget.pas',
  cda_base in '..\..\library\cda\cda_base.pas',
  cda_documents in '..\..\library\cda\cda_documents.pas',
  cda_narrative in '..\..\library\cda\cda_narrative.pas',
  cda_objects in '..\..\library\cda\cda_objects.pas',
  cda_parser in '..\..\library\cda\cda_parser.pas',
  cda_types in '..\..\library\cda\cda_types.pas',
  dicom_Dictionary in '..\..\library\dicom\dicom_Dictionary.pas',
  dicom_Extractor in '..\..\library\dicom\dicom_Extractor.pas',
  dicom_JpegLS in '..\..\library\dicom\dicom_JpegLS.pas',
  dicom_Objects in '..\..\library\dicom\dicom_Objects.pas',
  dicom_Parser in '..\..\library\dicom\dicom_Parser.pas',
  dicom_Writer in '..\..\library\dicom\dicom_Writer.pas',
  fsl_gdiplus in '..\..\library\ui\fsl_gdiplus.pas',
  FHIR.Support.Certs in '..\..\library\support\FHIR.Support.Certs.pas',
  fsl_collections in '..\..\library\support\fsl_collections.pas',
  fsl_threads in '..\..\library\support\fsl_threads.pas',
  fsl_graphics in '..\..\library\support\fsl_graphics.pas',
  fsl_html in '..\..\library\support\fsl_html.pas',
  fsl_json in '..\..\library\support\fsl_json.pas',
  fsl_xml in '..\..\library\support\fsl_xml.pas',
  fsl_base in '..\..\library\support\fsl_base.pas',
  fsl_ole in '..\..\library\support\fsl_ole.pas',
  fsl_printing_win in '..\..\library\support\fsl_printing_win.pas',
  fsl_shell in '..\..\library\support\fsl_shell.pas',
  FHIR.Support.Signatures in '..\..\library\support\FHIR.Support.Signatures.pas',
  fsl_stream in '..\..\library\support\fsl_stream.pas',
  fsl_utilities in '..\..\library\support\fsl_utilities.pas',
  fsl_wininet in '..\..\library\web\fsl_wininet.pas',
  fsl_xml in '..\..\library\support\fsl_xml.pas',
  fhir_ucum in '..\..\library\ucum\fhir_ucum.pas',
  FHIR.Uix.Advanced in '..\..\library\ui\FHIR.Uix.Advanced.pas',
  FHIR.Uix.Base in '..\..\library\ui\FHIR.Uix.Base.pas',
  FHIR.Uix.Controls in '..\..\library\ui\FHIR.Uix.Controls.pas',
  FHIR.Uix.Dialogs in '..\..\library\ui\FHIR.Uix.Dialogs.pas',
  FHIR.Uix.Forms in '..\..\library\ui\FHIR.Uix.Forms.pas',
  FHIR.Uix.Images in '..\..\library\ui\FHIR.Uix.Images.pas',
  FHIR.WP.Builder in '..\..\library\wp\FHIR.WP.Builder.pas',
  FHIR.WP.Cda in '..\..\library\wp\FHIR.WP.Cda.pas',
  FHIR.WP.Control in '..\..\library\wp\FHIR.WP.Control.pas',
  FHIR.WP.Definers in '..\..\library\wp\FHIR.WP.Definers.pas',
  FHIR.WP.Dialogs in '..\..\library\wp\FHIR.WP.Dialogs.pas',
  FHIR.WP.Document in '..\..\library\wp\FHIR.WP.Document.pas',
  FHIR.WP.Dragon in '..\..\library\wp\FHIR.WP.Dragon.pas',
  FHIR.WP.Engine in '..\..\library\wp\FHIR.WP.Engine.pas',
  FHIR.WP.FieldDefiners in '..\..\library\wp\FHIR.WP.FieldDefiners.pas',
  FHIR.WP.Handler in '..\..\library\wp\FHIR.WP.Handler.pas',
  FHIR.WP.Html in '..\..\library\wp\FHIR.WP.Html.pas',
  FHIR.WP.Icons in '..\..\library\wp\FHIR.WP.Icons.pas',
  FHIR.WP.Imaging in '..\..\library\wp\FHIR.WP.Imaging.pas',
  FHIR.WP.Menus in '..\..\library\wp\FHIR.WP.Menus.pas',
  FHIR.WP.Native in '..\..\library\wp\FHIR.WP.Native.pas',
  FHIR.WP.Odt in '..\..\library\wp\FHIR.WP.Odt.pas',
  FHIR.WP.Printing in '..\..\library\wp\FHIR.WP.Printing.pas',
  FHIR.WP.Renderer in '..\..\library\wp\FHIR.WP.Renderer.pas',
  FHIR.WP.Rtf in '..\..\library\wp\FHIR.WP.Rtf.pas',
  FHIR.WP.Settings in '..\..\library\wp\FHIR.WP.Settings.pas',
  FHIR.WP.Spelling in '..\..\library\wp\FHIR.WP.Spelling.pas',
  FHIR.WP.Text in '..\..\library\wp\FHIR.WP.Text.pas',
  FHIR.WP.Toolbar in '..\..\library\wp\FHIR.WP.Toolbar.pas',
  FHIR.WP.Types in '..\..\library\wp\FHIR.WP.Types.pas',
  FHIR.WP.Unicode in '..\..\library\wp\FHIR.WP.Unicode.pas',
  FHIR.WP.V2Ft in '..\..\library\wp\FHIR.WP.V2Ft.pas',
  FHIR.WP.Widgets in '..\..\library\wp\FHIR.WP.Widgets.pas',
  FHIR.WP.Working in '..\..\library\wp\FHIR.WP.Working.pas',
  fsl_fetcher in '..\..\library\web\fsl_fetcher.pas',
  fsl_mapi in '..\..\library\web\fsl_mapi.pas',
  GraphicColor in '..\..\dependencies\ui\GraphicColor.pas',
  GraphicCompression in '..\..\dependencies\ui\GraphicCompression.pas',
  GraphicEx in '..\..\dependencies\ui\GraphicEx.pas',
  GraphicStrings in '..\..\dependencies\ui\GraphicStrings.pas',
  JPG in '..\..\dependencies\ui\JPG.pas',
  MZLib in '..\..\dependencies\ui\MZLib.pas',
  ScintCDA in '..\..\dependencies\ui\ScintCDA.pas',
  ScintEdit in '..\..\dependencies\ui\ScintEdit.pas',
  ScintInt in '..\..\dependencies\ui\ScintInt.pas',
  cda_writer in '..\..\library\cda\cda_writer.pas',
  VirtualTrees in '..\..\dependencies\treeview\source\VirtualTrees.pas',
  VTAccessibilityFactory in '..\..\dependencies\treeview\source\VTAccessibilityFactory.pas',
  VirtualTrees.StyleHooks in '..\..\dependencies\treeview\source\VirtualTrees.StyleHooks.pas',
  VirtualTrees.Classes in '..\..\dependencies\treeview\source\VirtualTrees.Classes.pas',
  VirtualTrees.WorkerThread in '..\..\dependencies\treeview\source\VirtualTrees.WorkerThread.pas',
  VirtualTrees.ClipBoard in '..\..\dependencies\treeview\source\VirtualTrees.ClipBoard.pas',
  VirtualTrees.Utils in '..\..\dependencies\treeview\source\VirtualTrees.Utils.pas',
  VTHeaderPopup in '..\..\dependencies\treeview\source\VTHeaderPopup.pas',
  VirtualTrees.Export in '..\..\dependencies\treeview\source\VirtualTrees.Export.pas',
  FHIR.WP.AnnotationDefiners in '..\..\library\wp\FHIR.WP.AnnotationDefiners.pas',
  FHIR.WP.Snomed in '..\..\library\wp\FHIR.WP.Snomed.pas',
  CDEOptions in 'CDEOptions.pas' {CDEOptionsForm},
  OidFetcher in 'OidFetcher.pas' {OidFetcherForm},
  cdaHeaderForm in 'cdaHeaderForm.pas',
  IIEditor in 'IIEditor.pas' {IIEditForm},
  OIDCache in 'OIDCache.pas',
  fsl_fpc in '..\..\library\support\fsl_fpc.pas',
  FHIR.Support.Osx in '..\..\library\support\FHIR.Support.Osx.pas',
  v2_base in '..\..\library\v2\v2_base.pas',
  v2_dictionary in '..\..\library\v2\v2_dictionary_pas',
  v2_objects in '..\..\library\v2\v2_objects.pas',
  v2_publish in '..\..\library\v2\v2_publish.pas',
  FHIR.WP.Format in '..\..\library\wp\FHIR.WP.Format.pas',
  v2_conformance in '..\..\library\v2\v2_conformance.pas',
  MarkdownHTMLEntities in '..\..\..\markdown\source\MarkdownHTMLEntities.pas',
  VirtualTrees.AccessibilityFactory in '..\..\dependencies\treeview\Source\VirtualTrees.AccessibilityFactory.pas',
  VirtualTrees.HeaderPopup in '..\..\dependencies\treeview\Source\VirtualTrees.HeaderPopup.pas';

{$R *.RES}
{$R WindowsXP.RES}

Begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TWordProcessorForm, WordProcessorForm);
  Application.Run;
End.

