Program ClinicalDocumentEditor;

uses
  FastMM4 in '..\..\dependencies\FMM\FastMM4.pas',
  Forms,
  CDEForm in 'CDEForm.pas' {TWordProcessorForm},
  FastMM4Messages in '..\..\dependencies\FMM\FastMM4Messages.pas',
  DropBMPTarget in '..\..\dependencies\ui\DropBMPTarget.pas',
  DropSource in '..\..\dependencies\ui\DropSource.pas',
  DropTarget in '..\..\dependencies\ui\DropTarget.pas',
  FHIR.Cda.Base in '..\..\library\cda\FHIR.Cda.Base.pas',
  FHIR.Cda.Documents in '..\..\library\cda\FHIR.Cda.Documents.pas',
  FHIR.Cda.Narrative in '..\..\library\cda\FHIR.Cda.Narrative.pas',
  FHIR.Cda.Objects in '..\..\library\cda\FHIR.Cda.Objects.pas',
  FHIR.Cda.Parser in '..\..\library\cda\FHIR.Cda.Parser.pas',
  FHIR.Cda.Types in '..\..\library\cda\FHIR.Cda.Types.pas',
  FHIR.Dicom.Dictionary in '..\..\library\dicom\FHIR.Dicom.Dictionary.pas',
  FHIR.Dicom.Extractor in '..\..\library\dicom\FHIR.Dicom.Extractor.pas',
  FHIR.Dicom.JpegLS in '..\..\library\dicom\FHIR.Dicom.JpegLS.pas',
  FHIR.Dicom.Objects in '..\..\library\dicom\FHIR.Dicom.Objects.pas',
  FHIR.Dicom.Parser in '..\..\library\dicom\FHIR.Dicom.Parser.pas',
  FHIR.Dicom.Writer in '..\..\library\dicom\FHIR.Dicom.Writer.pas',
  FHIR.Ui.GdiPlus in '..\..\library\ui\FHIR.Ui.GdiPlus.pas',
  FHIR.Support.Certs in '..\..\library\support\FHIR.Support.Certs.pas',
  FHIR.Support.Collections in '..\..\library\support\FHIR.Support.Collections.pas',
  FHIR.Support.Threads in '..\..\library\support\FHIR.Support.Threads.pas',
  FHIR.Support.Graphics in '..\..\library\support\FHIR.Support.Graphics.pas',
  FHIR.Support.Html in '..\..\library\support\FHIR.Support.Html.pas',
  FHIR.Support.Json in '..\..\library\support\FHIR.Support.Json.pas',
  FHIR.Support.MXml in '..\..\library\support\FHIR.Support.MXml.pas',
  FHIR.Support.Base in '..\..\library\support\FHIR.Support.Base.pas',
  FHIR.Support.Ole in '..\..\library\support\FHIR.Support.Ole.pas',
  FHIR.Support.Printing in '..\..\library\support\FHIR.Support.Printing.pas',
  FHIR.Support.Shell in '..\..\library\support\FHIR.Support.Shell.pas',
  FHIR.Support.Signatures in '..\..\library\support\FHIR.Support.Signatures.pas',
  FHIR.Support.Stream in '..\..\library\support\FHIR.Support.Stream.pas',
  FHIR.Support.Utilities in '..\..\library\support\FHIR.Support.Utilities.pas',
  FHIR.Web.WinInet in '..\..\library\web\FHIR.Web.WinInet.pas',
  FHIR.Support.Xml in '..\..\library\support\FHIR.Support.Xml.pas',
  FHIR.Ucum.IFace in '..\..\library\ucum\FHIR.Ucum.IFace.pas',
  FHIR.Uix.Advanced in '..\..\library\ui\FHIR.Uix.Advanced.pas',
  FHIR.Uix.Base in '..\..\library\ui\FHIR.Uix.Base.pas',
  FHIR.Uix.Controls in '..\..\library\ui\FHIR.Uix.Controls.pas',
  FHIR.Uix.Dialogs in '..\..\library\ui\FHIR.Uix.Dialogs.pas',
  FHIR.Uix.Forms in '..\..\library\ui\FHIR.Uix.Forms.pas',
  FHIR.Uix.Images in '..\..\library\ui\FHIR.Uix.Images.pas',
  FHIR.WP.Builder in '..\..\library\wp\FHIR.WP.Builder.pas',
  FHIR.WP.Cda in '..\..\library\wp\FHIR.WP.Cda.pas',
  FHIR.WP.Control in '..\..\library\wp\FHIR.WP.Control.pas',
  FHIR.WP.Definers in '..\..\library\wp\FHIR.WP.Definers.pas',
  FHIR.WP.Dialogs in '..\..\library\wp\FHIR.WP.Dialogs.pas',
  FHIR.WP.Document in '..\..\library\wp\FHIR.WP.Document.pas',
  FHIR.WP.Dragon in '..\..\library\wp\FHIR.WP.Dragon.pas',
  FHIR.WP.Engine in '..\..\library\wp\FHIR.WP.Engine.pas',
  FHIR.WP.FieldDefiners in '..\..\library\wp\FHIR.WP.FieldDefiners.pas',
  FHIR.WP.Handler in '..\..\library\wp\FHIR.WP.Handler.pas',
  FHIR.WP.Html in '..\..\library\wp\FHIR.WP.Html.pas',
  FHIR.WP.Icons in '..\..\library\wp\FHIR.WP.Icons.pas',
  FHIR.WP.Imaging in '..\..\library\wp\FHIR.WP.Imaging.pas',
  FHIR.WP.Menus in '..\..\library\wp\FHIR.WP.Menus.pas',
  FHIR.WP.Native in '..\..\library\wp\FHIR.WP.Native.pas',
  FHIR.WP.Odt in '..\..\library\wp\FHIR.WP.Odt.pas',
  FHIR.WP.Printing in '..\..\library\wp\FHIR.WP.Printing.pas',
  FHIR.WP.Renderer in '..\..\library\wp\FHIR.WP.Renderer.pas',
  FHIR.WP.Rtf in '..\..\library\wp\FHIR.WP.Rtf.pas',
  FHIR.WP.Settings in '..\..\library\wp\FHIR.WP.Settings.pas',
  FHIR.WP.Spelling in '..\..\library\wp\FHIR.WP.Spelling.pas',
  FHIR.WP.Text in '..\..\library\wp\FHIR.WP.Text.pas',
  FHIR.WP.Toolbar in '..\..\library\wp\FHIR.WP.Toolbar.pas',
  FHIR.WP.Types in '..\..\library\wp\FHIR.WP.Types.pas',
  FHIR.WP.Unicode in '..\..\library\wp\FHIR.WP.Unicode.pas',
  FHIR.WP.V2Ft in '..\..\library\wp\FHIR.WP.V2Ft.pas',
  FHIR.WP.Widgets in '..\..\library\wp\FHIR.WP.Widgets.pas',
  FHIR.WP.Working in '..\..\library\wp\FHIR.WP.Working.pas',
  FHIR.Web.Fetcher in '..\..\library\web\FHIR.Web.Fetcher.pas',
  FHIR.Web.Mapi in '..\..\library\web\FHIR.Web.Mapi.pas',
  GraphicColor in '..\..\dependencies\ui\GraphicColor.pas',
  GraphicCompression in '..\..\dependencies\ui\GraphicCompression.pas',
  GraphicEx in '..\..\dependencies\ui\GraphicEx.pas',
  GraphicStrings in '..\..\dependencies\ui\GraphicStrings.pas',
  JPG in '..\..\dependencies\ui\JPG.pas',
  MZLib in '..\..\dependencies\ui\MZLib.pas',
  ScintCDA in '..\..\dependencies\ui\ScintCDA.pas',
  ScintEdit in '..\..\dependencies\ui\ScintEdit.pas',
  ScintInt in '..\..\dependencies\ui\ScintInt.pas',
  FHIR.Cda.Writer in '..\..\library\cda\FHIR.Cda.Writer.pas',
  VirtualTrees in '..\..\dependencies\treeview\source\VirtualTrees.pas',
  VTAccessibilityFactory in '..\..\dependencies\treeview\source\VTAccessibilityFactory.pas',
  VirtualTrees.StyleHooks in '..\..\dependencies\treeview\source\VirtualTrees.StyleHooks.pas',
  VirtualTrees.Classes in '..\..\dependencies\treeview\source\VirtualTrees.Classes.pas',
  VirtualTrees.WorkerThread in '..\..\dependencies\treeview\source\VirtualTrees.WorkerThread.pas',
  VirtualTrees.ClipBoard in '..\..\dependencies\treeview\source\VirtualTrees.ClipBoard.pas',
  VirtualTrees.Utils in '..\..\dependencies\treeview\source\VirtualTrees.Utils.pas',
  VTHeaderPopup in '..\..\dependencies\treeview\source\VTHeaderPopup.pas',
  VirtualTrees.Export in '..\..\dependencies\treeview\source\VirtualTrees.Export.pas',
  FHIR.WP.AnnotationDefiners in '..\..\library\wp\FHIR.WP.AnnotationDefiners.pas',
  FHIR.WP.Snomed in '..\..\library\wp\FHIR.WP.Snomed.pas',
  CDEOptions in 'CDEOptions.pas' {CDEOptionsForm},
  OidFetcher in 'OidFetcher.pas' {OidFetcherForm},
  cdaHeaderForm in 'cdaHeaderForm.pas',
  IIEditor in 'IIEditor.pas' {IIEditForm},
  OIDCache in 'OIDCache.pas',
  FHIR.Support.Fpc in '..\..\library\support\FHIR.Support.Fpc.pas',
  FHIR.Support.Osx in '..\..\library\support\FHIR.Support.Osx.pas',
  FHIR.v2.Base in '..\..\library\v2\FHIR.v2.Base.pas',
  FHIR.v2.Dictionary in '..\..\library\v2\FHIR.v2.Dictionary.pas',
  FHIR.V2.Objects in '..\..\library\v2\FHIR.V2.Objects.pas',
  FHIR.v2.Publish in '..\..\library\v2\FHIR.v2.Publish.pas',
  FHIR.WP.Format in '..\..\library\wp\FHIR.WP.Format.pas',
  FHIR.v2.Conformance in '..\..\library\v2\FHIR.v2.Conformance.pas';

{$R *.RES}
{$R WindowsXP.RES}

Begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TWordProcessorForm, WordProcessorForm);
  Application.Run;
End.

