Program ClinicalDocumentEditor;

uses
  FastMM4 in '..\..\dependencies\FMM\FastMM4.pas',
  Forms,
  CDEForm in 'CDEForm.pas' {TWordProcessorForm},
  FastMM4Messages in '..\..\dependencies\FMM\FastMM4Messages.pas',
  DropBMPTarget in '..\..\dependencies\ui\DropBMPTarget.pas',
  DropSource in '..\..\dependencies\ui\DropSource.pas',
  DropTarget in '..\..\dependencies\ui\DropTarget.pas',
  cda_base in '..\..\library\cda\cda_base.pas',
  cda_documents in '..\..\library\cda\cda_documents.pas',
  cda_narrative in '..\..\library\cda\cda_narrative.pas',
  cda_objects in '..\..\library\cda\cda_objects.pas',
  cda_parser in '..\..\library\cda\cda_parser.pas',
  cda_types in '..\..\library\cda\cda_types.pas',
  dicom_Dictionary in '..\..\library\dicom\dicom_Dictionary.pas',
  wp_loader_dicom in '..\..\library\wp\wp_loader_dicom.pas',
  dicom_JpegLS in '..\..\library\dicom\dicom_JpegLS.pas',
  dicom_Objects in '..\..\library\dicom\dicom_Objects.pas',
  dicom_Parser in '..\..\library\dicom\dicom_Parser.pas',
  dicom_Writer in '..\..\library\dicom\dicom_Writer.pas',
  wp_gdiplus in '..\..\library\wp\wp_gdiplus.pas',
  fsl_collections in '..\..\library\fsl\fsl_collections.pas',
  fsl_threads in '..\..\library\fsl\fsl_threads.pas',
  wp_graphics in '..\..\library\wp\wp_graphics.pas',
  fsl_html in '..\..\library\fsl\fsl_html.pas',
  fsl_crypto in '..\..\library\fsl\fsl_crypto.pas',
  fsl_openssl in '..\..\library\fsl\fsl_openssl.pas',
  fsl_json in '..\..\library\fsl\fsl_json.pas',
  fsl_xml in '..\..\library\fsl\fsl_xml.pas',
  fsl_base in '..\..\library\fsl\fsl_base.pas',
  fsl_ole in '..\..\library\fsl\fsl_ole.pas',
  wp_printing_win in '..\..\library\wp\wp_printing_win.pas',
  fsl_shell in '..\..\library\fsl\fsl_shell.pas',
  fsl_stream in '..\..\library\fsl\fsl_stream.pas',
  fsl_utilities in '..\..\library\fsl\fsl_utilities.pas',
  fsl_wininet in '..\..\library\fsl\fsl_wininet.pas',
  fsl_ucum in '..\..\library\fsl\fsl_ucum.pas',
  fui_vclx_Advanced in '..\..\library\fui\fui_vclx_Advanced.pas',
  fui_vclx_Base in '..\..\library\fui\fui_vclx_Base.pas',
  fui_vclx_Controls in '..\..\library\fui\fui_vclx_Controls.pas',
  fui_vclx_Dialogs in '..\..\library\fui\fui_vclx_Dialogs.pas',
  fui_vclx_Forms in '..\..\library\fui\fui_vclx_Forms.pas',
  fui_vclx_Images in '..\..\library\fui\fui_vclx_Images.pas',
  FHIR.WP.Builder in '..\..\library\wp\FHIR.WP.Builder.pas',
  FHIR.WP.Cda in '..\..\library\wp\FHIR.WP.Cda.pas',
  FHIR.WP.Control in '..\..\library\wp\FHIR.WP.Control.pas',
  wp_definers in '..\..\library\wp\wp_definers.pas',
  FHIR.WP.Dialogs in '..\..\library\wp\FHIR.WP.Dialogs.pas',
  wp_document in '..\..\library\wp\wp_document.pas',
  FHIR.WP.Dragon in '..\..\library\wp\FHIR.WP.Dragon.pas',
  FHIR.WP.Engine in '..\..\library\wp\FHIR.WP.Engine.pas',
  FHIR.WP.FieldDefiners in '..\..\library\wp\FHIR.WP.FieldDefiners.pas',
  FHIR.WP.Handler in '..\..\library\wp\FHIR.WP.Handler.pas',
  wp_html in '..\..\library\wp\wp_html.pas',
  FHIR.WP.Icons in '..\..\library\wp\FHIR.WP.Icons.pas',
  wp_imaging in '..\..\library\wp\wp_imaging.pas',
  FHIR.WP.Menus in '..\..\library\wp\FHIR.WP.Menus.pas',
  wp_native in '..\..\library\wp\wp_native.pas',
  wp_odt in '..\..\library\wp\wp_odt.pas',
  FHIR.WP.Printing in '..\..\library\wp\FHIR.WP.Printing.pas',
  FHIR.WP.Renderer in '..\..\library\wp\FHIR.WP.Renderer.pas',
  wp_rtf in '..\..\library\wp\wp_rtf.pas',
  FHIR.WP.Settings in '..\..\library\wp\FHIR.WP.Settings.pas',
  FHIR.WP.Spelling in '..\..\library\wp\FHIR.WP.Spelling.pas',
  wp_text in '..\..\library\wp\wp_text.pas',
  FHIR.WP.Toolbar in '..\..\library\wp\FHIR.WP.Toolbar.pas',
  wp_types in '..\..\library\wp\wp_types.pas',
  FHIR.WP.Unicode in '..\..\library\wp\FHIR.WP.Unicode.pas',
  FHIR.WP.V2Ft in '..\..\library\wp\FHIR.WP.V2Ft.pas',
  FHIR.WP.Widgets in '..\..\library\wp\FHIR.WP.Widgets.pas',
  wp_working in '..\..\library\wp\wp_working.pas',
  fsl_fetcher in '..\..\library\fsl\fsl_fetcher.pas',
  fsl_mapi in '..\..\library\fsl\fsl_mapi.pas',
  ScintCDA in '..\..\dependencies\ui\ScintCDA.pas',
  ScintEdit in '..\..\dependencies\ui\ScintEdit.pas',
  ScintInt in '..\..\dependencies\ui\ScintInt.pas',
  cda_writer in '..\..\library\cda\cda_writer.pas',
  VirtualTrees in '..\..\dependencies\treeview\source\VirtualTrees.pas',
  VTAccessibilityFactory in '..\..\dependencies\treeview\source\VTAccessibilityFactory.pas',
  VirtualTrees.StyleHooks in '..\..\dependencies\treeview\source\VirtualTrees.StyleHooks.pas',
  VirtualTrees.Classes in '..\..\dependencies\treeview\source\VirtualTrees.Classes.pas',
  VirtualTrees.WorkerThread in '..\..\dependencies\treeview\source\VirtualTrees.WorkerThread.pas',
  VirtualTrees.ClipBoard in '..\..\dependencies\treeview\source\VirtualTrees.ClipBoard.pas',
  VirtualTrees.Utils in '..\..\dependencies\treeview\source\VirtualTrees.Utils.pas',
  VTHeaderPopup in '..\..\dependencies\treeview\source\VTHeaderPopup.pas',
  VirtualTrees.Export in '..\..\dependencies\treeview\source\VirtualTrees.Export.pas',
  FHIR.WP.AnnotationDefiners in '..\..\library\wp\FHIR.WP.AnnotationDefiners.pas',
  FHIR.WP.Snomed in '..\..\library\wp\FHIR.WP.Snomed.pas',
  CDEOptions in 'CDEOptions.pas' {CDEOptionsForm},
  OidFetcher in 'OidFetcher.pas' {OidFetcherForm},
  cdaHeaderForm in 'cdaHeaderForm.pas',
  IIEditor in 'IIEditor.pas' {IIEditForm},
  OIDCache in 'OIDCache.pas',
  fsl_fpc in '..\..\library\fsl\fsl_fpc.pas',
  v2_base in '..\..\library\v2\v2_base.pas',
  v2_dictionary in '..\..\library\v2\v2_dictionary.pas',
  v2_objects in '..\..\library\v2\v2_objects.pas',
  v2_publish in '..\..\library\v2\v2_publish.pas',
  wp_format in '..\..\library\wp\wp_format.pas',
  v2_conformance in '..\..\library\v2\v2_conformance.pas',
  MarkdownHTMLEntities in '..\..\..\markdown\source\MarkdownHTMLEntities.pas',
  VirtualTrees.AccessibilityFactory in '..\..\dependencies\treeview\Source\VirtualTrees.AccessibilityFactory.pas',
  VirtualTrees.HeaderPopup in '..\..\dependencies\treeview\Source\VirtualTrees.HeaderPopup.pas',
  wp_clipboard in '..\..\library\wp\wp_clipboard.pas',
  wp_factory in '..\..\library\wp\wp_factory.pas',
  wp_graphics_ex in '..\..\library\wp\wp_graphics_ex.pas',
  GraphicColor in '..\..\dependencies\ui\GraphicColor.pas',
  GraphicCompression in '..\..\dependencies\ui\GraphicCompression.pas',
  GraphicEx in '..\..\dependencies\ui\GraphicEx.pas',
  GraphicStrings in '..\..\dependencies\ui\GraphicStrings.pas',
  JPG in '..\..\dependencies\ui\JPG.pas',
  MZLib in '..\..\dependencies\ui\MZLib.pas',
  wp_printing_base in '..\..\library\wp\wp_printing_base.pas';

{$R *.RES}
{$R WindowsXP.RES}

Begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TWordProcessorForm, WordProcessorForm);
  Application.Run;
End.

