program FhirVclDemo;

uses
  FastMM4 in '..\Libraries\FMM\FastMM4.pas' {Vcl.Forms},
  Vcl.Forms,
  MainApplicationWindow in 'MainApplicationWindow.pas' {MainWindowForm},
  SystemSupport in '..\reference-platform\support\SystemSupport.pas',
  DateSupport in '..\reference-platform\Support\DateSupport.pas',
  FastMM4Messages in '..\Libraries\FMM\FastMM4Messages.pas',
  StringSupport in '..\reference-platform\support\StringSupport.pas',
  MathSupport in '..\reference-platform\support\MathSupport.pas',
  GUIDSupport in '..\reference-platform\support\GUIDSupport.pas',
  DecimalSupport in '..\reference-platform\support\DecimalSupport.pas',
  EncodeSupport in '..\reference-platform\support\EncodeSupport.pas',
  FileSupport in '..\reference-platform\support\FileSupport.pas',
  MemorySupport in '..\reference-platform\support\MemorySupport.pas',
  AdvObjects in '..\reference-platform\support\AdvObjects.pas',
  AdvExceptions in '..\reference-platform\support\AdvExceptions.pas',
  AdvGenerics in '..\reference-platform\support\AdvGenerics.pas',
  AdvStringBuilders in '..\reference-platform\support\AdvStringBuilders.pas',
  AdvStreams in '..\reference-platform\support\AdvStreams.pas',
  AdvObjectLists in '..\reference-platform\support\AdvObjectLists.pas',
  AdvItems in '..\reference-platform\support\AdvItems.pas',
  AdvFilers in '..\reference-platform\support\AdvFilers.pas',
  ColourSupport in '..\reference-platform\support\ColourSupport.pas',
  CurrencySupport in '..\reference-platform\support\CurrencySupport.pas',
  AdvCollections in '..\reference-platform\support\AdvCollections.pas',
  AdvPersistents in '..\reference-platform\support\AdvPersistents.pas',
  AdvIterators in '..\reference-platform\support\AdvIterators.pas',
  FHIRBase in '..\reference-platform\support\FHIRBase.pas',
  AdvNames in '..\reference-platform\support\AdvNames.pas',
  AdvStringLists in '..\reference-platform\support\AdvStringLists.pas',
  AdvCSVFormatters in '..\reference-platform\support\AdvCSVFormatters.pas',
  AdvTextFormatters in '..\reference-platform\support\AdvTextFormatters.pas',
  AdvFormatters in '..\reference-platform\support\AdvFormatters.pas',
  AdvCSVExtractors in '..\reference-platform\support\AdvCSVExtractors.pas',
  AdvTextExtractors in '..\reference-platform\support\AdvTextExtractors.pas',
  AdvExtractors in '..\reference-platform\support\AdvExtractors.pas',
  AdvCharacterSets in '..\reference-platform\support\AdvCharacterSets.pas',
  AdvOrdinalSets in '..\reference-platform\support\AdvOrdinalSets.pas',
  AdvStreamReaders in '..\reference-platform\support\AdvStreamReaders.pas',
  AdvFiles in '..\reference-platform\support\AdvFiles.pas',
  ErrorSupport in '..\reference-platform\support\ErrorSupport.pas',
  AdvStringStreams in '..\reference-platform\support\AdvStringStreams.pas',
  BytesSupport in '..\reference-platform\support\BytesSupport.pas',
  AdvPersistentLists in '..\reference-platform\support\AdvPersistentLists.pas',
  AdvBuffers in '..\reference-platform\support\AdvBuffers.pas',
  ParserSupport in '..\reference-platform\support\ParserSupport.pas',
  FHIRUtilities in '..\reference-platform\dstu2\FHIRUtilities.pas',
  OIDSupport in '..\reference-platform\support\OIDSupport.pas',
  ParseMap in '..\reference-platform\support\ParseMap.pas',
  AdvVCLStreams in '..\reference-platform\support\AdvVCLStreams.pas',
  AdvMemories in '..\reference-platform\support\AdvMemories.pas',
  AdvJSON in '..\reference-platform\support\AdvJSON.pas',
  TextUtilities in '..\reference-platform\support\TextUtilities.pas',
  AdvZipWriters in '..\reference-platform\support\AdvZipWriters.pas',
  AdvNameBuffers in '..\reference-platform\support\AdvNameBuffers.pas',
  AdvObjectMatches in '..\reference-platform\support\AdvObjectMatches.pas',
  AdvZipDeclarations in '..\reference-platform\support\AdvZipDeclarations.pas',
  AdvZipParts in '..\reference-platform\support\AdvZipParts.pas',
  AdvZipUtilities in '..\reference-platform\support\AdvZipUtilities.pas',
  AdvZipWorkers in '..\reference-platform\support\AdvZipWorkers.pas',
  MimeMessage in '..\reference-platform\support\MimeMessage.pas',
  InternetFetcher in '..\reference-platform\support\InternetFetcher.pas',
  FHIRContext in '..\reference-platform\dstu2\FHIRContext.pas',
  FHIRTypes in '..\reference-platform\dstu2\FHIRTypes.pas',
  FHIRResources in '..\reference-platform\dstu2\FHIRResources.pas',
  FHIRSupport in '..\reference-platform\support\FHIRSupport.pas',
  AdvStringMatches in '..\reference-platform\support\AdvStringMatches.pas',
  JWT in '..\reference-platform\support\JWT.pas',
  HMAC in '..\reference-platform\support\HMAC.pas',
  libeay32 in '..\reference-platform\support\libeay32.pas',
  SCIMObjects in '..\reference-platform\support\SCIMObjects.pas',
  MXML in '..\reference-platform\support\MXML.pas',
  GraphQL in '..\reference-platform\support\GraphQL.pas',
  FHIRIndexBase in '..\reference-platform\support\FHIRIndexBase.pas',
  FHIRConstants in '..\reference-platform\dstu2\FHIRConstants.pas',
  FHIRSecurity in '..\reference-platform\support\FHIRSecurity.pas',
  FHIRTags in '..\reference-platform\dstu2\FHIRTags.pas',
  FHIRLang in '..\reference-platform\support\FHIRLang.pas',
  AfsResourceVolumes in '..\reference-platform\support\AfsResourceVolumes.pas',
  AfsVolumes in '..\reference-platform\support\AfsVolumes.pas',
  AdvStringHashes in '..\reference-platform\support\AdvStringHashes.pas',
  HashSupport in '..\reference-platform\support\HashSupport.pas',
  AdvHashes in '..\reference-platform\support\AdvHashes.pas',
  AfsStreamManagers in '..\reference-platform\support\AfsStreamManagers.pas',
  FHIRXhtml in '..\reference-platform\support\FHIRXhtml.pas',
  XMLBuilder in '..\reference-platform\support\XMLBuilder.pas',
  FHIRParser in '..\reference-platform\support\FHIRParser.pas',
  FHIRParserBase in '..\reference-platform\support\FHIRParserBase.pas',
  MXmlBuilder in '..\reference-platform\support\MXmlBuilder.pas',
  AdvXmlBuilders in '..\reference-platform\support\AdvXmlBuilders.pas',
  AdvXMLFormatters in '..\reference-platform\support\AdvXMLFormatters.pas',
  AdvXMLEntities in '..\reference-platform\support\AdvXMLEntities.pas',
  TurtleParser in '..\reference-platform\support\TurtleParser.pas',
  FHIRParserXml in '..\reference-platform\dstu2\FHIRParserXml.pas',
  FHIRParserJson in '..\reference-platform\dstu2\FHIRParserJson.pas',
  FHIRMetaModel in '..\reference-platform\dstu2\FHIRMetaModel.pas',
  FHIRProfileUtilities in '..\reference-platform\dstu2\FHIRProfileUtilities.pas',
  kCritSct in '..\reference-platform\support\kCritSct.pas',
  AdvZipReaders in '..\reference-platform\support\AdvZipReaders.pas',
  FHIRPath in '..\reference-platform\dstu2\FHIRPath.pas',
  FHIRClient in '..\reference-platform\client\FHIRClient.pas',
  AdvWinInetClients in '..\reference-platform\support\AdvWinInetClients.pas',
  SmartOnFhirUtilities in '..\reference-platform\client\SmartOnFhirUtilities.pas',
  CDSHooksUtilities in '..\reference-platform\support\CDSHooksUtilities.pas',
  MarkdownProcessor in '..\..\markdown\source\MarkdownProcessor.pas',
  MarkdownDaringFireball in '..\..\markdown\source\MarkdownDaringFireball.pas',
  MarkdownCommonMark in '..\..\markdown\source\MarkdownCommonMark.pas',
  ShellSupport in '..\reference-platform\support\ShellSupport.pas',
  SmartOnFhirLogin in '..\reference-platform\client\SmartOnFhirLogin.pas' {SmartOnFhirLoginForm};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TMainWindowForm, MainWindowForm);
  Application.CreateForm(TSmartOnFhirLoginForm, SmartOnFhirLoginForm);
  Application.Run;
end.
