program FHIRTransformer;

uses
  Vcl.Forms,
  FHIR.Transformer.IDE in 'FHIR.Transformer.IDE.pas' {TransformerForm},
  VirtualTrees.Actions in '..\dependencies\treeview\Source\VirtualTrees.Actions.pas',
  VirtualTrees.Classes in '..\dependencies\treeview\Source\VirtualTrees.Classes.pas',
  VirtualTrees.ClipBoard in '..\dependencies\treeview\Source\VirtualTrees.ClipBoard.pas',
  VirtualTrees.Export in '..\dependencies\treeview\Source\VirtualTrees.Export.pas',
  VirtualTrees in '..\dependencies\treeview\Source\VirtualTrees.pas',
  VirtualTrees.StyleHooks in '..\dependencies\treeview\Source\VirtualTrees.StyleHooks.pas',
  VirtualTrees.Utils in '..\dependencies\treeview\Source\VirtualTrees.Utils.pas',
  VirtualTrees.WorkerThread in '..\dependencies\treeview\Source\VirtualTrees.WorkerThread.pas',
  VTAccessibility in '..\dependencies\treeview\Source\VTAccessibility.pas',
  VTAccessibilityFactory in '..\dependencies\treeview\Source\VTAccessibilityFactory.pas',
  VTHeaderPopup in '..\dependencies\treeview\Source\VTHeaderPopup.pas',
  FHIR.Transformer.Workspace in 'FHIR.Transformer.Workspace.pas',
  FHIR.Support.Base in '..\library\support\FHIR.Support.Base.pas',
  FHIR.Support.Collections in '..\library\support\FHIR.Support.Collections.pas',
  FHIR.Support.Fpc in '..\library\support\FHIR.Support.Fpc.pas',
  FHIR.Support.Graphics in '..\library\support\FHIR.Support.Graphics.pas',
  FHIR.Support.Html in '..\library\support\FHIR.Support.Html.pas',
  FHIR.Support.Javascript in '..\library\support\FHIR.Support.Javascript.pas',
  FHIR.Support.Json in '..\library\support\FHIR.Support.Json.pas',
  FHIR.Support.Logging in '..\library\support\FHIR.Support.Logging.pas',
  FHIR.Support.MXml in '..\library\support\FHIR.Support.MXml.pas',
  FHIR.Support.Ole in '..\library\support\FHIR.Support.Ole.pas',
  FHIR.Support.Osx in '..\library\support\FHIR.Support.Osx.pas',
  FHIR.Support.Printing in '..\library\support\FHIR.Support.Printing.pas',
  FHIR.Support.Shell in '..\library\support\FHIR.Support.Shell.pas',
  FHIR.Support.Stream in '..\library\support\FHIR.Support.Stream.pas',
  FHIR.Support.Utilities in '..\library\support\FHIR.Support.Utilities.pas',
  FHIR.Support.Xml in '..\library\support\FHIR.Support.Xml.pas',
  GraphicColor in '..\dependencies\ui\GraphicColor.pas',
  GraphicCompression in '..\dependencies\ui\GraphicCompression.pas',
  GraphicEx in '..\dependencies\ui\GraphicEx.pas',
  GraphicStrings in '..\dependencies\ui\GraphicStrings.pas',
  JPG in '..\dependencies\ui\JPG.pas',
  MZLib in '..\dependencies\ui\MZLib.pas',
  FHIR.Scint.CDA in '..\library\ui\FHIR.Scint.CDA.pas',
  ScintEdit in '..\dependencies\ui\ScintEdit.pas',
  ScintInt in '..\dependencies\ui\ScintInt.pas',
  FHIR.Javascript.Base in '..\library\javascript\FHIR.Javascript.Base.pas',
  FHIR.Javascript.Chakra in '..\library\javascript\FHIR.Javascript.Chakra.pas',
  FHIR.Javascript in '..\library\javascript\FHIR.Javascript.pas',
  FHIR.Support.Threads in '..\library\support\FHIR.Support.Threads.pas',
  FHIR.Ui.GdiPlus in '..\library\ui\FHIR.Ui.GdiPlus.pas',
  FHIR.Cda.Base in '..\library\cda\FHIR.Cda.Base.pas',
  FHIR.Cda.Documents in '..\library\cda\FHIR.Cda.Documents.pas',
  FHIR.Cda.Narrative in '..\library\cda\FHIR.Cda.Narrative.pas',
  FHIR.Cda.Objects in '..\library\cda\FHIR.Cda.Objects.pas',
  FHIR.Cda.Parser in '..\library\cda\FHIR.Cda.Parser.pas',
  FHIR.Cda.Types in '..\library\cda\FHIR.Cda.Types.pas',
  FHIR.Cda.Writer in '..\library\cda\FHIR.Cda.Writer.pas',
  FHIR.Ucum.IFace in '..\library\ucum\FHIR.Ucum.IFace.pas',
  FHIR.Base.Common in '..\library\base\FHIR.Base.Common.pas',
  FHIR.Base.Lang in '..\library\base\FHIR.Base.Lang.pas',
  FHIR.Base.Objects in '..\library\base\FHIR.Base.Objects.pas',
  FHIR.Base.Parser in '..\library\base\FHIR.Base.Parser.pas',
  FHIR.Base.PathEngine in '..\library\base\FHIR.Base.PathEngine.pas',
  FHIR.Base.Utilities in '..\library\base\FHIR.Base.Utilities.pas',
  FHIR.Base.Xhtml in '..\library\base\FHIR.Base.Xhtml.pas',
  FHIR.Base.Factory in '..\library\base\FHIR.Base.Factory.pas',
  FHIR.Client.Base in '..\library\client\FHIR.Client.Base.pas',
  FHIR.Support.Turtle in '..\library\support\FHIR.Support.Turtle.pas',
  FHIR.Base.Narrative in '..\library\base\FHIR.Base.Narrative.pas',
  FHIR.Web.Parsers in '..\library\web\FHIR.Web.Parsers.pas',
  FHIR.Client.Javascript in '..\library\client\FHIR.Client.Javascript.pas',
  FHIR.Web.Fetcher in '..\library\web\FHIR.Web.Fetcher.pas',
  FHIR.Transformer.Utilities in 'FHIR.Transformer.Utilities.pas',
  FHIR.Ui.ListSelector in '..\library\ui\FHIR.Ui.ListSelector.pas' {ListSelectorForm},
  FHIR.Scint.Formats in '..\library\ui\FHIR.Scint.Formats.pas',
  FHIR.Cache.PackageManagerDialog in '..\library\cache\FHIR.Cache.PackageManagerDialog.pas' {PackageCacheForm},
  FHIR.Cache.PackageManager in '..\library\cache\FHIR.Cache.PackageManager.pas',
  FHIR.Cache.PackageBrowser in '..\library\cache\FHIR.Cache.PackageBrowser.pas' {PackageFinderForm},
  FHIR.Transformer.Engine in 'FHIR.Transformer.Engine.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TTransformerForm, TransformerForm);
  Application.CreateForm(TListSelectorForm, ListSelectorForm);
  Application.CreateForm(TPackageCacheForm, PackageCacheForm);
  Application.CreateForm(TPackageFinderForm, PackageFinderForm);
  Application.Run;
end.
