program FhirVclDemo;

uses
  FastMM4 in '..\..\dependencies\FMM\FastMM4.pas' {Vcl.Forms},
  SysUtils,
  IdSSLOpenSSLHeaders,
  Vcl.Forms,
  MainApplicationWindow in 'MainApplicationWindow.pas' {MainWindowForm},
  FastMM4Messages in '..\..\dependencies\FMM\FastMM4Messages.pas',
  fsl_utilities in '..\..\library\support\fsl_utilities.pas',
  fsl_base in '..\..\library\support\fsl_base.pas',
  fsl_stream in '..\..\library\support\fsl_stream.pas',
  fsl_collections in '..\..\library\support\fsl_collections.pas',
  fhir_objects in '..\..\library\base\fhir_objects.pas',
  fhir2_utilities in '..\..\library\r2\fhir2_utilities.pas',
  fsl_http in '..\..\library\web\fsl_http.pas',
  fsl_json in '..\..\library\support\fsl_json.pas',
  fsl_fetcher in '..\..\library\web\fsl_fetcher.pas',
  fhir2_context in '..\..\library\r2\fhir2_context.pas',
  fhir2_types in '..\..\library\r2\fhir2_types.pas',
  fhir2_resources in '..\..\library\r2\fhir2_resources.pas',
  fsl_scim in '..\..\library\base\fsl_scim.pas',
  fsl_xml in '..\..\library\support\fsl_xml.pas',
  FHIR.Tools.Indexing in '..\..\library\tools\FHIR.Tools.Indexing.pas',
  fhir2_constants in '..\..\library\r2\fhir2_constants.pas',
  FHIR.R2.Tags in '..\..\library\r2\FHIR.R2.Tags.pas',
  FHIR.Base.Lang in '..\..\library\base\FHIR.Base.Lang.pas',
  fhir_xhtml in '..\..\library\base\fhir_xhtml.pas',
  FHIR.Version.Parser in '..\..\library\version\FHIR.Version.Parser.pas',
  fhir_parser in '..\..\library\base\fhir_parser.pas',
  fsl_turtle in '..\..\library\support\fsl_turtle.pas',
  fhir2_xml in '..\..\library\r2\fhir2_xml.pas',
  fhir2_json in '..\..\library\r2\fhir2_json.pas',
  fhir2_elementmodel in '..\..\library\r2\fhir2_elementmodel.pas',
  fhir2_profiles in '..\..\library\r2\fhir2_profiles.pas',
  fsl_threads in '..\..\library\support\fsl_threads.pas',
  fhir2_pathengine in '..\..\library\r2\fhir2_pathengine.pas',
  FHIR.Version.Client in '..\..\library\version\FHIR.Version.Client.pas',
  fsl_wininet in '..\..\library\web\fsl_wininet.pas',
  fhir_cdshooks in '..\..\library\cdshooks\fhir_cdshooks.pas',
  MarkdownProcessor in '..\..\..\markdown\source\MarkdownProcessor.pas',
  MarkdownDaringFireball in '..\..\..\markdown\source\MarkdownDaringFireball.pas',
  MarkdownCommonMark in '..\..\..\markdown\source\MarkdownCommonMark.pas',
  fsl_shell in '..\..\library\support\fsl_shell.pas',
  fhir_ucum in '..\..\library\ucum\fhir_ucum.pas',
  fhir2_pathnode in '..\..\library\r2\fhir2_pathnode.pas',
  fhir2_base in '..\..\library\r2\fhir2_base.pas',
  fhir2_parser in '..\..\library\r2\fhir2_parser.pas',
  fhir2_parserBase in '..\..\library\r2\fhir2_parserBase.pas',
  fhir_client in '..\..\library\client\fhir_client.pas',
  fhir_client_http in '..\..\library\client\fhir_client_http.pas',
  fhir_client_threaded in '..\..\library\client\fhir_client_threaded.pas',
  fhir2_client in '..\..\library\r2\fhir2_client.pas',
  fsl_xml in '..\..\library\support\fsl_xml.pas',
  FHIR.Support.Certs in '..\..\library\support\FHIR.Support.Certs.pas',
  fsl_graphql in '..\..\library\web\fsl_graphql.pas',
  fhir_factory in '..\..\library\base\fhir_factory.pas',
  fhir_validator in '..\..\library\base\fhir_validator.pas',
  fhir_common in '..\..\library\base\fhir_common.pas',
  fhir_narrative in '..\..\library\base\fhir_narrative.pas',
  fhir2_common in '..\..\library\r2\fhir2_common.pas',
  FHIR.Support.Signatures in '..\..\library\support\FHIR.Support.Signatures.pas',
  fsl_fpc in '..\..\library\support\fsl_fpc.pas',
  fhir_utilities in '..\..\library\base\fhir_utilities.pas',
  fhir_oauth in '..\..\library\smart\fhir_oauth.pas',
  FHIR.Smart.Login in '..\..\library\smart\FHIR.Smart.Login.pas',
  FHIR.Smart.LoginVCL in '..\..\library\smart\FHIR.Smart.LoginVCL.pas' {SmartOnFhirLoginForm},
  fhir2_operations in '..\..\library\r2\fhir2_operations.pas',
  fhir2_opbase in '..\..\library\r2\fhir2_opbase.pas',
  FHIR.Support.Osx in '..\..\library\support\FHIR.Support.Osx.pas',
  fsl_logging in '..\..\library\support\fsl_logging.pas',
  fhir_oids in '..\..\library\base\fhir_oids.pas',
  fhir_elementmodel in '..\..\library\base\fhir_elementmodel.pas',
  MarkdownHTMLEntities in '..\..\..\markdown\source\MarkdownHTMLEntities.pas',
  fsl_npm_cache in '..\..\library\npm\fsl_npm_cache.pas',
  fsl_npm in '..\..\library\npm\fsl_npm.pas',
  FHIR.Npm.Client in '..\..\library\npm\FHIR.Npm.Client.pas',
  fhir_pathengine in '..\..\library\base\fhir_pathengine.pas',
  fhir2_resources_other in '..\..\library\r2\fhir2_resources_other.pas',
  fhir2_resources_clinical in '..\..\library\r2\fhir2_resources_clinical.pas',
  fhir2_resources_canonical in '..\..\library\r2\fhir2_resources_canonical.pas',
  fhir2_resources_base in '..\..\library\r2\fhir2_resources_base.pas',
  fhir2_resources_admin in '..\..\library\r2\fhir2_resources_admin.pas',
  MarkdownUnicodeUtils in '..\..\..\markdown\source\MarkdownUnicodeUtils.pas';

{$R *.res}

begin
  IdOpenSSLSetLibPath(extractFilePath(paramstr(0)));
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TMainWindowForm, MainWindowForm);
  Application.Run;
end.
